### ISSUE TITLE
Repo website URL leads to a 404 / HTTPS security warning

### ISSUE THREAD

**Issue by davidjb** [ODIQueensland/data-curator#1016]
### Current Behaviour (for problems)
https://theodi.org.au/data-curator/ (the repo website URL) leads to a HTTPS security certificate warning and if loaded over http:// leads to a 404.

### Expected Behaviour

Website should load or URL shouldn't be present.

Seems to also affect the main website URLs as shown at https://github.com/ODIQueensland.  Just thought you'd like to know.

### Steps to Reproduce

1. Click https://theodi.org.au/data-curator/

**Comment by mattRedBox** [comment]
Hi @davidjb 
Thanks - yes that organisation is well and truly defunct so I'm not suprised that there were certificate warnings - I'll remove the website link for now.
At the moment there is [a ticket open](https://github.com/ODIQueensland/data-curator/issues/1006), which we'll be raising with our sponsors to move the project under [qcif](https://github.com/qcif/).
If that proceeds, I guess I'll talk to the only other member of the repo, @Stephen-Gates about potentially archiving things here at some point (unless of course there is an upsurge of the 'Sharing Open Data movement'...somewhere, somehow 🤔 )
