### ISSUE TITLE
Make data table take all available screen space

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#103]
### Expected Behaviour
The Data table should take all available screen space

### Current Behaviour
The Data table doesn't take all available screen space

<img width="1440" alt="screenshot 2017-09-27 20 34 32" src="https://user-images.githubusercontent.com/9379524/30910483-4ea780c0-a3c8-11e7-9be2-681d1989c60a.png">

This is due to the table size being fixed https://github.com/ODIQueensland/data-curator/blob/develop/src/renderer/hot.js#L11 

This handsontable feature may also help pushing the scroll bars to the right and bottom edges of the screen https://docs.handsontable.com/0.34.4/demo-stretching.html

### Steps to Reproduce

1. Open Data Curator 
2. Add columns and rows
3. Resize the screen

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator 0.3.1 +  https://github.com/ODIQueensland/data-curator/commit/55430b7b605119436c04a1c3244cba357e7a6deb
* Operating System macOS Sierra 10.12.6

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
I think what you're saying is that you want the table to take up the entire screen, not actually just stretch the columns to the screen?

**Comment by Stephen-Gates** [comment]
@mattredbox Correct. Or alternatively anchor the scroll bar to the right of the main panel. However I think the scroll bar is attached to the table, so use the full space. If stretching helps, fine. If it can be achieved without stretching, also fine.

**Comment by mattRedBox** [comment]
Think it can be done without stretching

**Comment by Stephen-Gates** [comment]
@mattRedBox I'm not sure the fix worked 

<img width="796" alt="screenshot 2017-09-28 18 42 45" src="https://user-images.githubusercontent.com/9379524/30957203-f5bea82a-a47c-11e7-8413-0289b63525af.png">

**Comment by mattRedBox** [comment]
Hi Stephen the column property arrows I can deal with- must have touched something else in refactoring - but I'm not sure what the issue is with the real estate - did you not want it to take up whole screen?

**Comment by Stephen-Gates** [comment]
See the scroll bar in the image above - it's under the table.

When I invoke column properties, the scroll bar is hidden behind the right panel (macOS & Windows 7)

![win-hidden-scroll](https://user-images.githubusercontent.com/9379524/30994697-c2c61b2a-a4f8-11e7-8738-5b0e101221f0.PNG)
