### ISSUE TITLE
Enable entry of trueValues and falseValues for Boolean values

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#109]
### Expected Behaviour 
When I choose [`boolean`](http://specs.frictionlessdata.io/table-schema/#boolean) as a Type, allow me to enter trueValues and falseValues 

### Current Behaviour
I cannot enter trueValues and falseValues 

<img width="1075" alt="screenshot 2017-09-28 00 49 39" src="https://user-images.githubusercontent.com/9379524/30920620-caa3c37c-a3e7-11e7-8e72-b2551b137d89.png">

### Your Environment

* Data Curator version 0.3.1
* Operating System  macOS Sierra 10.12.6

**Comment by mattRedBox** [comment]
Sorry @Stephen-Gates 
Not sure what you mean. Atm, it just sets type without controlling what you can enter in the spreadsheet.

**Comment by Stephen-Gates** [comment]
The spec says,

> ### boolean
>
> The field contains boolean (true/false) data.
>
> In the physical representations of data where boolean values are represented with strings, the values set in `trueValues` and `falseValues` are to be cast to their logical representation as booleans. `trueValues` and `falseValues` are arrays which can be customised to user need. The default values for these are in the additional properties section below.
>
> The boolean field can be customised with these additional properties:
>
> * **trueValues**: `[ "true", "True", "TRUE", "1" ]`
> * **falseValues**: `[ "false", "False", "FALSE", "0" ]`
>
> `format`: no options (other than the default).
>

So I assume we need two input fields to accept `trueValues` and `falseValues`.

**Comment by Stephen-Gates** [comment]
Required when we implement Open Data Package function as the schema may include the trueValues and falseValues option

**Comment by Stephen-Gates** [comment]
/remind me to draft the user interface and acceptance tests on 18 April

**Comment by Stephen-Gates** [comment]
Thoughts on user interface: 

If `type` is `boolean`, allow entry of:

- An array of `trueValues` - default vales are [ "true", "True", "TRUE", "1" ]
- An array of `falseValues` - default vales are [ "false", "False", "FALSE", "0" ]

On screen help to guide input of values and show default values

**Comment by Stephen-Gates** [comment]
[Acceptance test](https://app.cucumber.pro/projects/data-curator/documents/branch/develop/test/features/tools/validate-table.feature#scenario-validate-boolean-truevalues-and-falsevalues-9
)

**Comment by mattRedBox** [comment]
Add input text box showing default values, which user can change.
Ensure this is sent with validation,export, etc.
Put input box between type and format.
