### ISSUE TITLE
“DataCurator.app” can’t be opened because it is from an unidentified developer

### ISSUE THREAD

**Issue by sjackman** [ODIQueensland/data-curator#111]
### Expected Behaviour (for problems)

Open the app.

### Current Behaviour

Displays…

> “DataCurator.app” can’t be opened because it is from an unidentified developer.
Your security preferences allow installation of only apps from the Mac App Store and identified developers.

### Steps to Reproduce
> When reporting a problem, provide a set of steps so others can reproduce the problem.

1. Open Data Curator using the icon

or

1. Right click on the icon, hold option, select Open
2. `“DataCurator.app” is from an unidentified developer. Are you sure you want to open it?`
3. Select Open
4. Prompt opens requesting the administrator password. I don't have administrator access on this machine. Click cancel.

### Your Environment

* Data Curator version 0.3.1
* macOS El Capitan
* User account with administrator access

**Comment by Stephen-Gates** [comment]
Thanks for reporting this @sjackman and I'm sorry you're unable to run Data Curator.

Signing the app is [planned](https://github.com/ODIQueensland/data-curator/milestone/5) but not currently implemented.

Without Admin access to your Mac, I don't think you can run the app. 

@mattRedBox any suggestions?

**Comment by sjackman** [comment]
I can try DataCurator out at home on my laptop; I just can't use it at work. Glad to hear that signing the app is on your plan.

**Comment by Stephen-Gates** [comment]
Great! Be aware that over the next week there’ll be quite a few releases as we actively squash bugs. If you find any, please let us know

**Comment by Stephen-Gates** [comment]
For others reading this, here's some screenshots and a work around if you have appropriate rights

1. Download and Install Data Curator
2. Attempt to run

<img width="421" alt="screenshot 2017-10-02 07 24 29" src="https://user-images.githubusercontent.com/9379524/31059403-04e2ac32-a745-11e7-9f72-764760ad0c53.png">

3. Go to the `Applications` folder in Finder
4. Right Click Data Curator and choose `Open`

<img width="422" alt="screenshot 2017-10-02 07 25 00" src="https://user-images.githubusercontent.com/9379524/31059419-2bdf2216-a745-11e7-9b81-fc012f3faf62.png">

4. Choose `Open` and Data Curator opens

**Comment by mattRedBox** [comment]
1.0.0 release is code-signed for both windows and mac
