### ISSUE TITLE
Can open Keyboard Shortcuts multiple times

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#112]
### Expected Behaviour 
I can only open keyboard shortcuts once

### Current Behaviour
I can only open keyboard shortcuts multiple times

<img width="808" alt="screenshot 2017-09-29 08 04 38" src="https://user-images.githubusercontent.com/9379524/30995216-06510686-a4fc-11e7-879e-86bb85e30a1d.png">

### Steps to Reproduce
> When reporting a problem, provide a set of steps so others can reproduce the problem.

1. Open Data Curator using the icon
2. Click Keyboard shortcuts
3. Click Keyboard shortcuts again

### Your Environment

* Data Curator version 0.3.2
* Operating System macOS Sierra 10.12.6

**Comment by Stephen-Gates** [comment]
Related to #60?

**Comment by mattRedBox** [comment]
No - already fixed, but did remove the windows menu.
