### ISSUE TITLE
Guess Column Properties inconsistent guesses

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#114]
### Expected Behaviour 
Column type should be guessed correctly

### Current Behaviour
The first column is guessed as Type: Any

<img width="797" alt="screenshot 2017-09-29 22 04 19" src="https://user-images.githubusercontent.com/9379524/31015256-81e9f490-a562-11e7-9451-eb2592c01537.png">

### Steps to Reproduce

1. Open Data Curator using the icon
2. Enter only integer data
3. Column 1 type = any
4. Column 2 & 3 type = integer

### Your Environment

* Data Curator version 0.3.3
* Operating System  macOS Sierra 10.12.6

**Comment by Stephen-Gates** [comment]
Guessing a second time doesn't update column properties

**Comment by mattRedBox** [comment]
Think this may be that no overwrite behaviour

**Comment by mattRedBox** [comment]
With the logic in place, I've switched over to: 'Guess Column Properties overwrites existing column values (no prompt yet if that is needed, and no other alternative e.g., guess but don't overwrite existing).
Missing values in.

**Comment by mattRedBox** [comment]
Still to fix remaining bug: need to force view update. Guess column properties will update values OK, but then need to deselect and reselect cell to see column properties flyout updated.
