### ISSUE TITLE
Quit (some work unsaved) behaviour doesn't match acceptance test

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#117]
### Expected Behaviour 

https://github.com/ODIQueensland/data-curator/blob/master/test/features/data_curator/quit.feature

### Current Behaviour

If I create data and have not saved my work, when I quit the Application I receive a prompt:

<img width="779" alt="screenshot 2017-09-30 06 59 56" src="https://user-images.githubusercontent.com/9379524/31035887-1123c286-a5ad-11e7-806a-60e9c63ce503.png">

- If I select Save from the prompt, the data isn't saved
- If I select Quit, the application quits

### Steps to Reproduce
- as above

### Your Environment

* Data Curator version 0.3.3
* Operating System macOS Sierra 10.12.6

**Comment by Stephen-Gates** [comment]
Save now works but only one tab saved. I think we should drop the save button

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Yep I agree. Kinda doesn't make sense to just save one tab. Easier to just cancel (so user can pick what to save) or quit.

**Comment by Stephen-Gates** [comment]
@mattRedBox Just tested this and I don't see a warning about unsaved work.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
As discussed previously, I don't put this in develop, because of the pain this causes with hot reload.
My understanding was that you were testing against release artifacts from master (ie: production), not against develop branch (which is not stable).

**Comment by Stephen-Gates** [comment]
Ok will test after release
