### ISSUE TITLE
Make Description box in Column Properties larger or expandable

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#129]
### Expected Behaviour 

When I enter a `description` of a column, I want to see it all in the Column Properties panel.
The text entry space should allow for multi-line entry and the text entry box should be expandable with a "widget" the the bottom right corner e.g.

<img width="167" alt="screenshot 2017-10-04 05 58 36" src="https://user-images.githubusercontent.com/9379524/31146201-298d2d48-a8c9-11e7-91f3-ca6f39edb147.png">

### Current Behaviour

The space for the `description` is very small and prevents me from easily viewing or editing the property.

<img width="381" alt="screenshot 2017-10-04 05 55 39" src="https://user-images.githubusercontent.com/9379524/31146013-ad0e1d04-a8c8-11e7-9b69-47d97a9cce36.png">

### Steps to Reproduce

1. Open Data Curator using the icon
2. Select Column Properties from the tool bar
3. See the tiny `description` box

### Your Environment

* Data Curator version 0.3.3
* Operating System macOS High Sierra 10.13

**Comment by Stephen-Gates** [comment]
Also applies to `description` in

- table properties
- package properties

See: https://vuejs.org/v2/guide/forms.html#Multiline-text

**Comment by mattRedBox** [comment]
@Stephen-Gates, yes can add enhancement here to make this textarea instead. 

Only extra needed will be that we will need to persist the settings of resized container as every time the panel collapses, the object is destroyed, losing the resized dimensions, and then re-created again on opening, reverting to default setting. Presume this is what you want (ie: to keep resized dimensions on any text area)? Note that this also means that opening and closing csv tabs will lose these resizes, again reverting to default.

**Comment by Stephen-Gates** [comment]
@mattRedBox sounds good

**Comment by mattRedBox** [comment]
changing this to autoresize to fit contents as something not quite right with min-height and height in textareas.

**Comment by Stephen-Gates** [comment]
resolved 🎉
