### ISSUE TITLE
Scroll bar hidden under Column Properties

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#131]
### Desired Behaviour 
When column properties is shown, the scroll bar should be pushed to the right of the Column Properties panel

### Current Behaviour
Scroll bar hidden under Column Properties

![scrollbarhidden](https://user-images.githubusercontent.com/9379524/31156115-be3df6bc-a8f5-11e7-92b2-b7df735d468c.png)

**Comment by mattRedBox** [comment]
Fixed 0.5.3
