### ISSUE TITLE
Support tab delimited TSV [feature request]

### ISSUE THREAD

**Issue by sjackman** [ODIQueensland/data-curator#14]
Please consider supporting reading and writing tab delimited (TSV) files.

**Comment by pwalsh** [comment]
This is supported by [CSV Dialect](http://specs.frictionlessdata.io/csv-dialect/) so it should not be a problem.

**Comment by Stephen-Gates** [comment]
@sjackman thanks for the suggestion. This is currently on our backlog and yes, @pwalsh shouldn't be hard. We have a limited budget so have had to prioritise. Here are our [planned milestones](https://github.com/ODIQueensland/data-curator/milestones?direction=asc&sort=due_date&state=open).

I'm in the process of adding acceptance tests through to milestone 0.5.0. We have 8 further sprints planned but currently unfunded. [Contributions of all types welcome](https://github.com/ODIQueensland/data-curator/blob/master/.github/CONTRIBUTING.md).

**Comment by Stephen-Gates** [comment]
Acceptance test for save as TSV [drafted here](https://github.com/ODIQueensland/data-curator/blob/0a8931425f46b0526c165f8650ecf4c8227d5845/test/features/save-as.feature). Feedback welcome.

**Comment by sjackman** [comment]
Great! Thanks, Stephen.

**Comment by Stephen-Gates** [comment]
Note only variant is dialect is the `delimiter` 
see https://discuss.okfn.org/t/profile-for-tab-or-semicolon-separated-value-files/5817?u=stephen

**Comment by Stephen-Gates** [comment]
Done!
