### ISSUE TITLE
Missing values written incorrectly to datapackage.json

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#141]
### Expected Behaviour 

Multiple missing values can be defined for the table as per http://specs.frictionlessdata.io/table-schema/#missing-values 

### Current Behaviour

One the first missing value is used

![image](https://user-images.githubusercontent.com/9379524/31262513-c2d8c094-aa9e-11e7-8aba-17b62aab6be7.png)

### Steps to Reproduce
see above

### Your Environment

* Data Curator version 0.3.5
* Operating System Windows 7

**Comment by Stephen-Gates** [comment]
Note potential change in spec https://github.com/frictionlessdata/specs/issues/551

**Comment by Stephen-Gates** [comment]
Found the problem, In v0.8.0 missingValues is written incorrectly to the Schema and correctly to the Resource. It should only be written to the Schema.

<img width="479" alt="screenshot 2017-12-31 16 27 47" src="https://user-images.githubusercontent.com/9379524/34459844-90d09ea4-ee47-11e7-91de-ec131fe8c881.png">

**Comment by mattRedBox** [comment]
The structure of the the exported schema is possibly a separate issue. 
At the moment, we only add missing values as a table property, according to spec. So don't think validation does much against column.
With note that this may change to cascade to column properties (and is already implemented as such in tableschema.js), we can also put this in to column properties and use validation.

**Comment by Stephen-Gates** [comment]
Note two missingValues entries in JSON above

**Comment by mattRedBox** [comment]
Wrong issue closed.
