### ISSUE TITLE
Provide "pick list" of tables and fields for Foreign and Primary Keys

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#152]
### Desired Behaviour 

Allow the user to select from a list of valid table or field names to specify the [Foreign ](http://specs.frictionlessdata.io/table-schema/#foreign-keys)and [Primary Keys](http://specs.frictionlessdata.io/table-schema/#primary-key).

Support the selection of multiple fields for keys by adding like the current sources function

**Comment by mattRedBox** [comment]
Implemented for Primary keys in release 0.5.2
