### ISSUE TITLE
Performance very slow on Windows 7

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#155]
### Expected Behaviour (for problems)

No lag in data entry. 
Reasonable speed in opening data or guessing column properties

### Current Behaviour

Significantly slower than 0.36

### Your Environment

* Data Curator version 0.4.0
* Operating System Windows 7

**Comment by mattRedBox** [comment]
Not sure there is too much we can do about this specifically for Windows 7. Any chance this is a 32bit machine (as electron with latest chromium known not to play nice with anything other than 64 bit)?
