### ISSUE TITLE
Remove Comma Chameleon references from code

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#17]
After initial merge from Comma Chameleon, there are still a couple of references that need to be removed. e.g. Menu Item names

https://github.com/ODIQueensland/data-curator/search?utf8=%E2%9C%93&q=Chameleon&type=

Specifically:

- this lizard image from the [css background](https://github.com/ODIQueensland/data-curator/blob/21b4f652a9c89ebea0c00bc1f2a3b29615f903bf/static/assets/css/default.css#L2)
- About and Hide Comma Chameleon [menu items](https://github.com/ODIQueensland/data-curator/blob/21b4f652a9c89ebea0c00bc1f2a3b29615f903bf/src/main/menu.js#L48)
-

**Comment by mattRedBox** [comment]
Yep think we've got this done now.
