### ISSUE TITLE
Next / Prev Column arrows don't recognise a column has been added

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#189]
### Expected Behaviour (for problems)

When I add or remove a column, the next/previous arrows should be hidden/made visible to reflect new valid / invalid options

### Current Behaviour

After adding a column, the next arrow is not enabled 

<img width="972" alt="screenshot 2017-10-31 07 18 28" src="https://user-images.githubusercontent.com/9379524/32247593-86c7c82c-bece-11e7-9129-66cb51a2b8e7.png">

### Your Environment

* Data Curator version 0.4.0
* Operating System and version  macOS High Sierra 10.13

**Comment by vitorbaptista** [comment]
I had a similar issue doing:

1. Open Data Curator
2. Remove one of the 3 empty columns that are created by default

You'll notice that there'll be a Next arrow even when you're on the last column (column 2). Clicking on it does nothing.

**Comment by Stephen-Gates** [comment]
Hi @vitorbaptista, great to see you here. 

Our last sprint prior to v1.0.0 will be fixing bugs in [this order](https://github.com/ODIQueensland/data-curator/milestone/9). There'll be some tension between fully supporting all the FrictionlessData features (e.g. bareNumber) and getting some basic features working (e.g. wiring up all the menu items). 

Thanks for reporting the Next arrow in the last column issue.
