### ISSUE TITLE
Changing column header cell updates column name property

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#197]
### Desired Behaviour 

When editing the column properties, column “name” can’t be edited.  It takes the value from the header row of the dataset.  This is good.  However, if I change the header cell in the dataset, the column “name” does not update.  I have to click “Guess Column Properties” to update the column “name” which resets all other properties I’ve already set.  It would be good if the column “name” property updates when focus leaves the header cell.

**Comment by mattRedBox** [comment]
Fixed for next release.
