### ISSUE TITLE
Import Column Properties

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#206]
### Desired Behaviour (for feature requests only)
As described at https://relishapp.com/odi-australia/data-curator/docs/backlog/import-column-properties

**Comment by Stephen-Gates** [comment]
A possible approach to providing a library of schema snippets https://github.com/Stephen-Gates/table-schema-snippets

**Comment by Stephen-Gates** [comment]
May not be needed if implement #852

**Comment by mattRedBox** [comment]
Hi @markwheels 
Split out from #852, to do the work required for Column Properties import, as I want to make sure that I've understood correctly.

> My question is what happens when the number of columns in the CSV and Table Schema are not equal? We may need some extra validation because at the moment these can't be different.
I presume you're talking about the column properties imported? 

Thinking yes that's the simplest way to go (unless I've misunderstood this?)

- make it strict by ensuring current table and import both match

**Comment by markwheels** [comment]
Thank @mattRedBox  and @Stephen-Gates , I have added the 'support:Approved' label.
