### ISSUE TITLE
null Sources properties written to datapackage.json 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#209]
### Expected Behaviour (for problems)
properties without values entered in the properties panel are not written to datapackage.json

### Current Behaviour
data package sources properties without values entered in the properties panel are written to datapackage.json

### Steps to Reproduce
> When reporting a problem, provide a set of steps so others can reproduce the problem.

1. Create a data package - don't enter optional or recommended property values
2. Export data package
3. Inspect datapackage.json

### Your Environment

* Data Curator version 0.5.0
* Operating System and version macOS High Sierra 10.13

**Comment by Stephen-Gates** [comment]
Nulls in the Sources property is invalid. The [spec](https://frictionlessdata.io/specs/data-package/#optional-properties) states that each Source must have a `title`.

**Comment by mattRedBox** [comment]
@Stephen-Gates,
So does that rule (ie: source must be present and must have at least title) also apply to each table?

**Comment by Stephen-Gates** [comment]
Yes https://frictionlessdata.io/specs/data-resource/#optional-properties

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Just tested this again and I put in the requirement because of the return from frictionless libraries. of error message:

"Descriptor validation error:
        Array is too short (0), minimum 1
        at "/sources" in descriptor and
        at "/properties/sources/minItems" in profile"

if either table or package does not have any sources.

**Comment by Stephen-Gates** [comment]
thanks @mattRedBox can you raise an issue for that as it appears to clash with the spec

**Comment by mattRedBox** [comment]
Sorry - that one's on me :P 
We were sending through an empty array of sources, so json validation at frictionless end was simply reporting cannot have empty array.
