### ISSUE TITLE
All resources in an exported data package should be tabular data resources

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#211]
### Current Behaviour
resources do not have the correct `profile` (tabular data resource) or `format` (tsv, csv)

### Steps to Reproduce
> When reporting a problem, provide a set of steps so others can reproduce the problem.

1. Create a data package with two tables
2. Save one table as csv, the other as tsv
3. Export data package
4. Inspect datapackage.json

<img width="385" alt="screenshot 2017-11-12 20 05 18" src="https://user-images.githubusercontent.com/9379524/32697850-5393cc92-c7e5-11e7-80e2-4d4c9fa43e34.png">

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version 0.5.0
* Operating System and version e.g. macOS High Sierra 10.13

**Comment by mattRedBox** [comment]
Sorry @Stephen-Gates having trouble replicating this. Can you give me example of data that you loaded that could produce this?

**Comment by Stephen-Gates** [comment]
@mattRedBox just made this data package https://github.com/Stephen-Gates/data-package-examples/blob/master/zip/csvtsv.zip 

Problem still exists but maybe it's not a problem give we're not doing CSVDialect correctly http://frictionlessdata.io/specs/tabular-data-resource/#csv-dialect 

Without describing the Tab as a delimiter, I don't think it's tabular.

If you agree, can close this issue.

**Comment by mattRedBox** [comment]
@Stephen-Gates, Issue was in code, with default table properties not setting for all- regardless of what we're not doing with csvdialect yet. Should be fixed, with both resources in example you provided showing tabular-data-resource.
