### ISSUE TITLE
Validation results inconsistent - first row ignored

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#219]
### Expected Behaviour (for problems)

type, format and constraints validate correctly 

### Current Behaviour

<img width="797" alt="screenshot 2017-11-15 22 05 43" src="https://user-images.githubusercontent.com/9379524/32835363-82f1374a-ca51-11e7-95e2-851882709078.png">

<img width="902" alt="screenshot 2017-11-15 23 15 31" src="https://user-images.githubusercontent.com/9379524/32837930-17e5b264-ca5b-11e7-9c13-81f300d16996.png">

<img width="642" alt="screenshot 2017-11-15 23 14 45" src="https://user-images.githubusercontent.com/9379524/32837939-230e1492-ca5b-11e7-9157-263a51a7f377.png">

### Your Environment

* Data Curator version 0.5.1
* Operating System and version  macOS High Sierra 10.13

**Comment by Stephen-Gates** [comment]
v0.5.4 

<img width="1265" alt="screenshot 2017-11-29 21 02 03" src="https://user-images.githubusercontent.com/9379524/33372215-e6e19b6c-d548-11e7-97dd-78b6616365f7.png">

**Comment by Stephen-Gates** [comment]
@mattRedBox seems to be the first row after the header row is being ignored.

Note no errors in row 1 reported.

Errors in row 2, labelled as row 1 errors 

<img width="661" alt="screenshot 2017-11-29 21 11 13" src="https://user-images.githubusercontent.com/9379524/33372463-dfb6442c-d549-11e7-9198-82cc5cd330ba.png">

**Comment by mattRedBox** [comment]
yep there's problem with row count.
