### ISSUE TITLE
Main panel freezes, menu still functions

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#222]
### Steps to Reproduce

unknown. occurs after extended use.

### Your Environment

* Data Curator version 0.5.1
* Operating System and version macOS High Sierra 10.13.1

**Comment by Stephen-Gates** [comment]
Seems to occur after Export Data Package

**Comment by Stephen-Gates** [comment]
Froze after save as command

<img width="965" alt="screenshot 2017-11-18 09 29 00" src="https://user-images.githubusercontent.com/9379524/32973409-045ae90a-cc43-11e7-8272-b9298dc00c23.png">

<img width="783" alt="screenshot 2017-11-18 09 30 39" src="https://user-images.githubusercontent.com/9379524/32973436-2f51e44c-cc43-11e7-9884-7d291ea3111e.png">

**Comment by Stephen-Gates** [comment]
frozen after guess column properties

**Comment by mattRedBox** [comment]
Rewrote Column properties to avoid set/get clashes causing infinite loop.
