### ISSUE TITLE
Validate that Constraints have associated values

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#258]
### Desired Behaviour (for feature requests only)

If one of the following constraint types are entered, ensure there is at least one associated value

- minLength
- maxLength
- minimum 
- maximum 
- pattern 
- enum

**Comment by Stephen-Gates** [comment]
Message for min and max is not quite right as it applies to date, time, year, etc https://frictionlessdata.io/specs/table-schema/#constraints 
<img width="359" alt="screenshot 2018-01-19 20 12 59" src="https://user-images.githubusercontent.com/9379524/35145905-2ff1898c-fd55-11e7-9263-6c3d68777e4c.png">

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Did we not decide we weren't going to validate on date and let user put in what they want?

**Comment by Stephen-Gates** [comment]
@mattRedBox we decided for Type: Date, Format: Pattern, we weren't going to attempt to validate that the Pattern complies with [standard Python / C strptime](https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior) because you said the regex was too complicated.

**Comment by mattRedBox** [comment]
@Stephen-Gates ,
Sorry I'm confused by your comment:
'Message for min and max is not quite right as it applies to date, time, year, etc'
We can't set a a validation message on date, time, year if we're not doing validation.
Atm for type, 'date' no validation appears - is this what you see in your test?

**Comment by Stephen-Gates** [comment]
Sorry I thought were talking about something else. On a bus. Will check tonight

**Comment by Stephen-Gates** [comment]
<img width="368" alt="screenshot 2018-01-24 19 38 45" src="https://user-images.githubusercontent.com/9379524/35325105-80d6b98e-013e-11e8-8661-804ad7b14e44.png">

<img width="371" alt="screenshot 2018-01-24 19 49 11" src="https://user-images.githubusercontent.com/9379524/35325527-ba2e723e-013f-11e8-8857-1b51eb601010.png">

Min / Max message looks good but we lost the enum message.

Is it possible to create a regex to validate that we have valid regex in the pattern constraint?

**Comment by mattRedBox** [comment]
Ok can correct enum.
re: regex. Not sure it's worth it, considering you could put almost anything in? We could throw the regex against a regex library, but don't know if any of them absolutely follow the w3 std, but perl 5. If we're being consistent with what we're doing with pattern for date, should we not just again let this go through to frictionless?

**Comment by Stephen-Gates** [comment]
Agreed
