### ISSUE TITLE
Header Row setting does not adjust across data tabs

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#259]
### Current Behaviour (for problems)
When a Header row is set to checked, It applies to all data tabs however the setting value is not reflected in each data tab.

### Expected Behaviour

Header row setting is applied to separately each data tab

### Your Environment

* Data Curator version: 0.5.2
* Operating System and version: Windows

**Comment by Stephen-Gates** [comment]
For future version we should discuss how this is best implemented.

I'm thinking:
- show Header Row in Table Properties. 
- two-way interaction between menu item and header row table property

**Comment by mattRedBox** [comment]
Yes @Stephen-Gates agreed - this is what I was also thinking to implement here.
