### ISSUE TITLE
Column properties not updated immediately after Guess Column Properties

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#263]
### Current Behaviour (for problems)

With the Column Properties panel showing, after Guess Column Properties the Column properties are not updated for the column displayed. 

If you move to another column and then return to the original column, the values are updated

### Expected Behaviour
Column properties are updated immediately after being changed

### Your Environment

* Data Curator version: 0.5.2
* Operating System and version: Windows 7

**Comment by Stephen-Gates** [comment]
Related to #134 

- if column properties panel is open, update values immediately
- if column properties panel is closed, open the panel

**Comment by mattRedBox** [comment]
Have observable that we use for keeping column names up-to-date. Need to add/enhance observable to grab all column properties (not just names), while keeping column name observer in place for foreign keys/primary keys.
