### ISSUE TITLE
Header row values not assigned to column name on Guess

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#267]
### Current Behaviour (for problems)
Header row values not assigned to column `name` on Guess Column Properties

### Expected Behaviour
Header row values are assigned to column `name` on Guess Column Properties

### Your Environment

* Data Curator version: 0.5.3 in Dev
* Operating System and version: macOS High Sierra 10.13.1

**Comment by mattRedBox** [comment]
Our mandatort 'asterisk' screwed up the property name :D. Will fix

**Comment by Stephen-Gates** [comment]
Thanks @mattRedBox - all good now
