### ISSUE TITLE
Required and Unique constraints being ignored in Validation 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#270]
### Current Behaviour (for problems)
Required and Unique constraints being ignored in Validation but written to datapackage.json

### Expected Behaviour
Required and Unique constraints are used in Validation 

### Your Environment

* Data Curator version: 0.5.4
* Operating System and version: macOS High Sierra 10.13.1

**Comment by Stephen-Gates** [comment]
Behaviour is inconsistent!

**Comment by mattRedBox** [comment]
Think required might be related, but unique I cannot trigger at all. Do you have example of when this constraint works?
From what I can see in tableschema.js 'required' is implemented, but not unique':

(from tableschema/lib/constraints/unique.js:)
`function checkUnique() {
  return true;
}`

You can see here it always returns that it is unique - a check is not actually performed.
These sort of values (ie: constraints) we send straight through without alteration.

**Comment by mattRedBox** [comment]
Closing, as unique is for frictionless, but yes think #219 should have sorted problem with 'required' now.
