### ISSUE TITLE
Primary Key is unique is not validated

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#272]
### Current Behaviour (for problems)
<img width="782" alt="screenshot 2017-11-29 21 34 38" src="https://user-images.githubusercontent.com/9379524/33373355-463218e0-d54d-11e7-8245-7fca840f93da.png">

### Expected Behaviour
Primary Key is validated to ensure it is unique.

See table schema.js https://github.com/frictionlessdata/tableschema-js/blob/f8539f5326caff210d4653ac5446144e596a067c/src/profiles/table-schema.json#L1443 

### Your Environment

* Data Curator version: 0.5.4
* Operating System and version: macOS High Sierra 10.13.1

**Comment by mattRedBox** [comment]
Need to check: who handles the potential sync (if PK is only 1 field) between table primary key and the column unique constraint.

**Comment by mattRedBox** [comment]
Simple fix.
