### ISSUE TITLE
Highlight validation errors

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#275]
### Desired Behaviour (for feature requests only)

- https://relishapp.com/odi-australia/data-curator/docs/tools/validate-table
- needs error rowNumber and columnNumber from [TableSchema.js](https://relishapp.com/odi-australia/data-curator/docs/tools/validate-table) to pin-point error location

<img width="419" alt="screenshot 2017-12-02 13 35 02" src="https://user-images.githubusercontent.com/9379524/33511383-a064aa66-d765-11e7-870f-04680910c8f9.png">

**Comment by Stephen-Gates** [comment]
Adjust error message at [Home.vue #L97](https://github.com/ODIQueensland/data-curator/blob/develop/src/renderer/components/Home.vue#L97) to include columnNumber, e.g.

```
              <h3>{{messagesTitle}}</h3>
              <template  v-if="messagesType === 'error'">
                <div v-for="errorMessage in messages">
                  <span v-show="errorMessage.rowNumber">Row {{errorMessage.rowNumber}}, </span>
                  <span v-show="errorMessage.columnNumber"> Column {{errorMessage.columnNumber}}, </span>
                  <span>{{errorMessage.message}}</span>
                </div>
              </template>
```

Potentially include hyperlink in rowNumber, columnNumber to cell in table (see #280)

**Comment by mattRedBox** [comment]
So we could:

- use hot's comments to add the markers
- they can stay until someone re-validates

**Comment by Stephen-Gates** [comment]
From #388 consider highlighting cell and adding error message as comment - https://docs.handsontable.com/0.35.0/demo-comments_.html#example

Bottom Status bar becomes Validation Success / Fail.

**Comment by Stephen-Gates** [comment]
Watch for progress on https://github.com/frictionlessdata/specs/issues/364

**Comment by Stephen-Gates** [comment]
Works 🎉 

<img width="796" alt="screenshot 2018-03-21 19 59 53" src="https://user-images.githubusercontent.com/9379524/37703784-84ac84e6-2d42-11e8-992f-8685bc4891a6.png">
