### ISSUE TITLE
Display total number of errors found

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#278]
reported by tester...

### Desired Behaviour (for feature requests only)

I wanted to get an idea of how many errors but there was no counter telling me I have X number of errors.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
I can put a number in - but is this behaviour still ok knowing that it doesn't actually capture ALL the errors - as for example field cast only captures 1 error at a time in frictionless?

**Comment by Stephen-Gates** [comment]
Good point @mattRedBox It can probably be addressed with some careful wording, e.g.

> This validation detected 32 errors. Other errors may be reported after these errors are resolved

What do you think @louisjasek?

**Comment by Stephen-Gates** [comment]
Fixed 

<img width="382" alt="screenshot 2018-03-24 16 23 29" src="https://user-images.githubusercontent.com/9379524/37861174-d57e08d8-2f7f-11e8-8fc3-a78cfb3ddb7a.png">
