### ISSUE TITLE
Link error message to cell

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#280]
a tester requests... Is there a possibility of a Find or sort function within the errors?

### Desired Behaviour (for feature requests only)

Wondering if this would be addressed by:

- clicking on a error message and moving the cursor to the error location 
- validate by column to isolate errors #267

**Comment by mattRedBox** [comment]
So we could:

- use hot's comments to add the markers
- they can stay until someone re-validates

**Comment by Stephen-Gates** [comment]
works 🎉 

<img width="615" alt="screenshot 2018-03-21 20 01 38" src="https://user-images.githubusercontent.com/9379524/37703842-b38b8528-2d42-11e8-9f11-9fe3dca214f8.png">
