### ISSUE TITLE
Increase unit test coverage

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#283]
To increase confidence in making code changes and to encourage other code contributors, significantly increase unit test coverage to that it is clear if a code change has broken any existing functionality.

**Comment by Stephen-Gates** [comment]
Include one end-to-end test

**Comment by Stephen-Gates** [comment]
Show before and after code coverage

**Comment by Stephen-Gates** [comment]
`@impl` tag being used to indicate which tests have been implemented

**Comment by Stephen-Gates** [comment]
@mattRedBox what changes are needed for https://github.com/ODIQueensland/data-curator#tests ?

**Comment by mattRedBox** [comment]
@Stephen-Gates 
I've updated the README.md
Note: Spent time on acceptance test boilerplate, rather than unit test
Note: haven't put in relish step or put into CI yet.
But, have added what I need to get me through main process interaction for now (including context menu, Application menu and dialog interactions).
Will merge dependabot PRs and upgrade electron to latest 8 with next dev version (just to ensure this release stability).

**Comment by Stephen-Gates** [comment]
Thanks Matt
Do you want me to create an issue for the above in v0.12.0?

**Comment by mattRedBox** [comment]
No need - it's a BAU task which is always on my plate.

**Comment by mattRedBox** [comment]
Just as a reference:
Part of issue with spectron and main process (ie: serialisation):
- https://github.com/electron/spectron/issues/21
The library we use to mock the dialogs (effectively intercept, close and return value):
[spectron-fake-dialog](https://github.com/joe-re/spectron-fake-dialog)
With more exploration, better ideas may emerge, but this library and the way it handles main code is useful, perhaps to duplicate for other main process stumbling blocks -  and will get us through for now (until Spectron perhaps do more to take care of this side of things).

**Comment by mattRedBox** [comment]
Just keeping open until we actually achieve signficant coverage

**Comment by Stephen-Gates** [comment]
See also https://github.com/ODIQueensland/data-curator/issues/594 as 1 way to publicly demonstrate coverage

**Comment by louisjasek** [comment]
@Stephen-Gates @mattRedBox has this issue been closed?

**Comment by mattRedBox** [comment]
No - frameworks are setup, but coverage not where it could be/should be.
