### ISSUE TITLE
Open file from Finder/Explorer in Data Curator by default

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#285]
### Desired Behaviour 

Hopefully after signing the application (#111 and #274) Data Curator will be able to be selected as the default application to open .csv and .tsv files. If not, this feature will do the work to _make it so_.

<img width="975" alt="screenshot 2017-12-02 17 53 38" src="https://user-images.githubusercontent.com/9379524/33513229-2c5a46ba-d78a-11e7-81f8-b041a35bd388.png">

[Acceptance test](https://app.cucumber.pro/projects/data-curator/documents/branch/develop/test/features/other/open-with.feature)

**Comment by Stephen-Gates** [comment]
It seems even after signing the app, more work is needed to make this happen 

<img width="420" alt="Screenshot 2019-05-31 21 45 45" src="https://user-images.githubusercontent.com/9379524/58703915-99109780-83ed-11e9-875d-2e5eb360622f.png">

**Comment by mattRedBox** [comment]
In Mac OSX, should be fixed with #848. Not sure yet if listener also available in Window.
