### ISSUE TITLE
Foreign key relationship is not validated 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#302]
Related to #300 ?

### Current Behaviour (for problems)
I create a foreign key relationship. Validate. No errors reported, however data contains errors

### Expected Behaviour
Validation reports FK errors

### Your Environment

* Data Curator version: 0.7.0
* Operating System and version: e.g. Windows 7

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Wasn't able to include feature for validation yet - (I removed it from release notes).
I already use the frictionless naming underneath so once I send the property through shouldn't take much to get going.

**Comment by mattRedBox** [comment]
Little bit more involved as frictionless libraries requires adding relations in map format before validation (cannot just add foreign keys to descriptor alone). Won't make this release.

**Comment by mattRedBox** [comment]
Work completed.
But also dependent on frictionlessdata/tableschema-js#124
