### ISSUE TITLE
Open datapackage.zip 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#304]
### Current Behaviour (for problems)
On opening a datapackage.zip file a few issues occur

![open-dp](https://user-images.githubusercontent.com/9379524/33700524-82ab3b62-db65-11e7-8f18-22ca315f9462.PNG)

![image](https://user-images.githubusercontent.com/9379524/33700647-309e0998-db66-11e7-8cd1-33f8104af5a0.png)

1. an extra data tab is opened
2. Column widths aren't automatically sized to match data
3. `Import Data Package Success` message should be `Open Data Package Success` to match the menu item name

(sorry to bundle 3 issues into 1)

### Your Environment

* Data Curator version: 0.7.0
* Operating System and version: Windows 7

**Comment by Stephen-Gates** [comment]
/remind me to refine the acceptance test to add de-referencing schema, dialect and data in 1 week

**Comment by Stephen-Gates** [comment]
See #411

**Comment by mattRedBox** [comment]
@Stephen-Gates 

1. This behaviour is as it should be. The application has no way of knowing whether there is existing data or not in the existing tab. Opening a new tab ensures nothing is accidentally overwritten.
2. Could you give me a dataset to re-test against. I've opened a QLD Govt dataset, and the columns seem to be resizing correctly
3. Fixed.

**Comment by Stephen-Gates** [comment]
Any of these zip files should work https://github.com/frictionlessdata/example-data-packages/tree/master/zip 

Did you see in the screen print when I open duration-test.zip it also opens ._duration-test? Two tabs for the one zip file.

**Comment by Stephen-Gates** [comment]
Works fine as far as I can tell 🎉
