### ISSUE TITLE
Unique constraint is not validated

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#311]
### Current Behaviour (for problems)
- open https://github.com/Stephen-Gates/data-package-examples/blob/master/zip/test-time.zip
- validate
- unique constraint error not detected

### Expected Behaviour
- error detected 

### Your Environment

* Data Curator version: 0.7.0
* Operating System and version: e.g. macOS High Sierra 10.13.1

**Comment by Stephen-Gates** [comment]
See https://github.com/frictionlessdata/tableschema-js/issues/122

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
In investigating this, I also noticed that while I can get multiple errors back from the same row.
I cannot get multiple errors back from same cell from tableschema.js - do we care about this?

i.e., The fact that the cell reports 1 error is enough, and that can be fixed, before the next one comes through - so we don't need it to report that multiple errors exit on the cell, just that there's an error is enough. 
Put another way: a cell only seems to report 1 error at a time.
You can test this by say putting in a minimum constraint and a 'required' constraint say on a blank cell of field: integer.

**Comment by Stephen-Gates** [comment]
@mattRedBox I think that's ok. 

/remind me to add Data Curator only reports 1 error per cell to the docs in 3 months time

**Comment by mattRedBox** [comment]
Tested changes successfully in our code needed for 
https://github.com/frictionlessdata/tableschema-js/pull/124
to get all row errors and also show unique constraints.

**Comment by Stephen-Gates** [comment]
@mattRedBox https://github.com/frictionlessdata/tableschema-js/releases/tag/v1.7.0 is out. 

Suggest this is now unblocked and can be included in 0.10.0 build?

**Comment by mattRedBox** [comment]
Fixed with 1.7.0 release
Nice work @roll
