### ISSUE TITLE
On Opening a file, set Table Property name

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#316]
### Current Behaviour 
On Opening a separated value file or Excel sheet, the Table Property `name` is not set. It is only set when the file is saved.

### Expected Behaviour
On Opening a separated value file or Excel sheet, set Table Property `name` using the filename without the extension.

### Your Environment

* Data Curator version: 0.7.0
* Operating System and version: e.g. Windows 7

**Comment by Stephen-Gates** [comment]
Need to make sure if this is implemented that is doesn't impact the check to ensure all data tabs have been saved.

**Comment by Stephen-Gates** [comment]
Currently only sets Tab name but not Table Property name

**Comment by mattRedBox** [comment]
Re-tested, can see Table name on opening file.
