### ISSUE TITLE
Side and Bottom panel should push (not cover) main content

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#317]
### Desired Behaviour (for feature requests only)
Side and Bottom panels should push and resize main content rather than cover it. This way the table scroll bars remain accessible. 

### Current Behaviour (for problems)
Scroll bars are covered when panels are open

![image](https://user-images.githubusercontent.com/9379524/33862443-7f04f332-df2e-11e7-8106-34c5a1cd62c6.png)

### Your Environment

* Data Curator version: 0.7.0
* Operating System and version: e.g. Windows & MacOS

**Comment by mattRedBox** [comment]
@Stephen-Gates, From the title, it suggests that this is also happening with side panels - which some code was added for - is this a bug in the side panels?
From the example, it looks like you want this enhancement for the bottom panel (where it hasn't existed) - so yes can change this.

**Comment by Stephen-Gates** [comment]
Thanks Matt I’ll get the side panels again to make sure they’re working. I recall different behaviour depending on the width of the data

**Comment by Stephen-Gates** [comment]
1. Create a new data tab
2. Add columns beyond width of screen -> scroll bar appears :heavy_check_mark: 
3. Add rows beyond the height of the screen -> -> scroll bar appears :heavy_check_mark: 
4. Select Column from toolbar -> side panel opens, vertical scroll bar disappears :cry: 
5. Select Validate from toolbar -> bottom panel opens, all scroll bars disappears :sob: 
6. Close bottom panel -> horizontal scroll bar no longer covered :smile: 
7. Close side panel -> vertical scroll bar no longer covered :smile: 
8. Open side panel
9. Resize window
10. Close side panel -> table not resized

![image](https://user-images.githubusercontent.com/9379524/34806931-91c7147c-f6d1-11e7-9323-1aac7cd379de.png)

**Comment by mattRedBox** [comment]
Thanks @Stephen-Gates 
Nice icons :)
There is a bit of an issue with re-rendering - not sure if it's within our stuff or hot yet.
For points 4 and 10:
On Mac (haven't checked what this looks like on Windows yet), with a bit of fidgeting in the cell, the scrollbar or resize occurs again - will look at what we can do here.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
The issue for the side navigation panel not immediately showing toolbars seems OK to me now.
However, still to handle the bottom covering content (didn't make it in the release :( )

**Comment by Stephen-Gates** [comment]
Thanks @mattRedBox. Do you want to close this and open another issue or leave as is?
