### ISSUE TITLE
Column property styling

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#323]
### Current Behaviour (for problems)
Need to allow a little more room for constraint values

![image](https://user-images.githubusercontent.com/9379524/33969717-90228660-e0ba-11e7-943a-793df4d0e5d7.png)

### Your Environment

* Data Curator version: 0.8.0
* Operating System and version: Windows 7

**Comment by Stephen-Gates** [comment]
Works fine on macOS

Just needs a tweak in https://github.com/ODIQueensland/data-curator/blob/develop/static/css/columnprops.styl#L18

**Comment by Stephen-Gates** [comment]
Probably best to drop `[ ] required` below the `Constraints` label. This would allow extra space for potentially long constraints in `pattern` or `enum`

**Comment by mattRedBox** [comment]
Seems to be a difference between dev and prod environments - will look into.
