### ISSUE TITLE
Unable to remove Primary Key

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#325]
### Current Behaviour (for problems)
If I select a primary key by mistake, I can't deselect it 

### Expected Behaviour
I can deselect a primary key value

### Your Environment

* Data Curator version: 0.8.0
* Operating System and version: Windows 7

**Comment by mattRedBox** [comment]
@Stephen-Gates can't replicate this in dev on mac.
Are you holding Ctrl/Command when trying to de-select? This is the standard way of deselecting with multiple select boxes. Changing this default behaviour can be done simply, but it's a bit of a hack - unless you want to change this the long way around and use checkboxes instead?

**Comment by Stephen-Gates** [comment]
Ok. Will update tool tip to explain and leave user interface as is.

**Comment by Stephen-Gates** [comment]
Fixed via https://github.com/ODIQueensland/data-curator/commit/fbe024d0dd58ca6043da36cacc1335b06f3ef11b
