### ISSUE TITLE
Tab styling

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#35]
### Current Behaviour 

The Tab close button is a bit loud.
<img width="266" alt="screenshot 2017-08-12 18 35 19" src="https://user-images.githubusercontent.com/9379524/29239235-298c0e64-7f8d-11e7-817e-c50482dcc1c6.png">

Also Tab baseline should match panel header baseline

<img width="798" alt="tab-alignment" src="https://user-images.githubusercontent.com/9379524/29407958-a92e281e-8389-11e7-8e6d-6df811aeda25.png">

### Expected Behaviour
- change colour of `X` to grey
- remove background colour (red)
- show `X` on hover over Tab
- hide `X` when no hover over Tab
- shade inactive Tabs a darker colour than the active Tab (e.g. the current hover over colour)
- baselines align e.g.

<img width="1440" alt="screenshot 2017-08-17 20 13 02" src="https://user-images.githubusercontent.com/9379524/29408218-b3b91068-838a-11e7-9d21-e50d93877d10.png">

**Comment by mattRedBox** [comment]
OK will line this up and #38 for next release.

**Comment by Stephen-Gates** [comment]
Essentially fixed. Very minor styling issue remains
<img width="554" alt="screenshot 2017-09-08 06 56 10" src="https://user-images.githubusercontent.com/9379524/30184986-194642c8-9463-11e7-9bee-ea18ad9c02b9.png">

**Comment by Stephen-Gates** [comment]
Remaining styling issue - remove background from close buttons

### Current behaviour
Inactive tab, No hover:
<img width="238" alt="screenshot 2017-09-08 06 56 20" src="https://user-images.githubusercontent.com/9379524/30185037-46ae2122-9463-11e7-8b3b-555dfd2d1b23.png">

on hover over close on inactive tab:
<img width="238" alt="screenshot 2017-09-08 06 56 29" src="https://user-images.githubusercontent.com/9379524/30185073-6267ff64-9463-11e7-9aeb-23588fd4b0d5.png">

### Expected behaviour

- close button not shown on active tab
- on hover over active tab, close button shown
- close button not shown on inactive tabs
- on hover over inactive tab:
  - close button shown
  - tab shaded
 - <img width="238" alt="screenshot 2017-09-08 06 56 29" src="https://user-images.githubusercontent.com/9379524/30185202-ddee5f98-9463-11e7-8ce7-85dc7e785103.png">
