### ISSUE TITLE
Toolbar styling

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#36]
The toolbar includes backlog items - `Find and Replace` and `Publish` 

<img width="901" alt="screenshot 2017-08-12 21 51 37" src="https://user-images.githubusercontent.com/9379524/29240428-75b34dc8-7fa8-11e7-9735-26f2b0b118f3.png">

`Data-curator` should be `Data Curator`

Toolbar should not have a border line and white background should match toolbar colour. e.g. 

<img width="779" alt="screenshot 2017-08-12 21 50 11" src="https://user-images.githubusercontent.com/9379524/29240421-4ef6142c-7fa8-11e7-8255-edf4b1f3f179.png">

**Comment by Stephen-Gates** [comment]
Column icon now available https://github.com/ODIQueensland/data-curator/blob/develop/static/img/column-properties.svg

**Comment by mattRedBox** [comment]
All completed.
