### ISSUE TITLE
Keep dependencies up to date (monthly)

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#365]
### Desired Behaviour 

Each month [Dependabot](https://dependabot.com) automatically creates a number of [Pull Requests tagged Dependencies](https://github.com/ODIQueensland/data-curator/pulls?q=is%3Aopen+is%3Apr+label%3Adependencies) to help keep code dependencies up-to-date.

Each PR should be reviewed and if appropriate tested and merged.

**Comment by mattRedBox** [comment]
/remind me to update dependencies in CI branch then merge back to develop and master for every 1 month

**Comment by mattRedBox** [comment]
/remind me to update dependencies in CI branch then merge back to develop and master in 1 month
