### ISSUE TITLE
Position of Validate button in toolbar? 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#371]
One tester suggested the Validate button should be the second last button, just before Export. This is what is currently implemented

![image](https://user-images.githubusercontent.com/9379524/34591810-d3e15f90-f20b-11e7-8f9d-8935cf8d58e0.png)

Another tester has suggested that Validate be after the Column button. After you've defined column properties, the next thing you'd typically do is validate the data.

 What do you think is the best approach?

**Comment by mattRedBox** [comment]
1 way to look at it:
- Validation is a task that is always after the task of entering any OR all of  Column, Table, Provenance and Package Properties, and so should remain where it is.

**Comment by Stephen-Gates** [comment]
Agreed
