### ISSUE TITLE
Make embedded help more obvious

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#372]
One tester commented about not understanding the meaning of some properties. I pointed out the embedded help that appears when you hover over a label

![image](https://user-images.githubusercontent.com/9379524/34591952-ab13bd50-f20c-11e7-937e-b90a5e4cf675.png)

It was suggested to add a icon to each field to make the help more obvious. 

![image](https://user-images.githubusercontent.com/9379524/34592094-68a3b23a-f20d-11e7-9f08-e2f8b8d36ebf.png)

What do you think? This could result in a lot of help icons on the screen ![info_icon](https://user-images.githubusercontent.com/9379524/34592275-8df18eb2-f20e-11e7-9bd3-12ec427c8b79.png)

Whatever is decided, it's probably worth adding:
- individual help for each type of constraint
- placeholder text for constraint values (especially pattern and enum)

**Comment by mattRedBox** [comment]
If we use a symbol for help (like the ? and i symbols above), yeah it could look a little noisy with them placed almost everywhere in properties. Making the icon more subtle or 'ghosty' might help? Or we provide a more generic help somewhere else (like a 'tips' that rolls through in status bar on open) that informs user to hover over the labels for help.
Some other apps often don't worry users possibly missing this clue (e.g., Atom, Slack) - assumes that hovering over a label for more help is intuitive.

**Comment by Stephen-Gates** [comment]
wont fix
