### ISSUE TITLE
Don't apply responsive design to panels

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#39]
Panels should be a fixed percentage of the screen width and not drop in a responsive menu button at small sizes.

Drop button labels as width reduces.

Take styling clues and behaviours from Slack App (mac OS)

<img width="475" alt="screenshot 2017-08-12 22 11 50" src="https://user-images.githubusercontent.com/9379524/29240578-791fec52-7fab-11e7-97c1-09a80ff87d93.png">

**Comment by mattRedBox** [comment]
done.
