### ISSUE TITLE
Add residual errors to readme.md

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#393]
### Desired Behaviour

If publishing invalid data is allowed, add residual errors to readme.md (or to a .json or .csv depending on https://github.com/frictionlessdata/specs/issues/364) 

To discuss at next sprint planning meeting.

**Comment by Stephen-Gates** [comment]
@louisjasek @mattRedBox do you have a view on this feature?

At the end of a Validation step, I'm thinking append the errors to the end of the README.md file

```
### Known Data Errors

This data is published with the following data errors:

Error message 1
...
Error message n
```

I'm concerned that:
- we don't know if the data was changed but not validated before the export
- that people may not look at the provenance as the export currently fails if no provenance is entered

**Comment by louisjasek** [comment]
Yeh that's a good point. I guess what is worse for the user?

- correct data with potentially incorrect error reporting
- potentially incorrect data without error reporting

@mattRedBox as a developer, what would you least prefer?

**Comment by Stephen-Gates** [comment]
See #388 for suggestion giving user control of adding error messages to readme

**Comment by mattRedBox** [comment]
Hi
@Stephen-Gates , @louisjasek 
For residual errors:
-  do users have to have these published with the the metadata?
    - if it's not compulsory, then we should just allow the user to choose:
      - if they wish to validate (prompt just before the publishing)
      - if they wish to add the errors to the metadata.
   - if it is compulsory, then we should automatically validate right before publishing and add these errors silently to the metadata.
- compulsory or not compulsory could also be an option in settings/preferences later

I'm not sure I understand why a person needs to look at the provenance report? I guess just making it clear in the how-tos that whatever the process is, is enough. Or we could somehow track whether the provenance data is simply error collation and remind the user that they haven't added their own data - and check that this is OK before export/publish.

**Comment by Stephen-Gates** [comment]
I’ve suggested that the user has control in #388. 

If we add automatically then the error that currently shows when no provenance information is present will not appear. I like this error as it prompts users to think about this. 

I guess at some stage we could get fancy and track if data changes after writing errors to readme and warn of potentially incorrect provenance information

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
There's possibly a way to keep the data added by user and errors separate. We may be able to show the errors as a read-only display, but keep the logic for user entry separate - I guess it's more about the business logic -> is a provenance file with only errors in it, valid? That should determine whether the user still gets prompted.

**Comment by Stephen-Gates** [comment]
Makes sense. Protect errors from being changed. Allow user to remove block of errors. Overwrite errors on next "write errors to provenance" command.

**Comment by Stephen-Gates** [comment]
Invoke "write errors to provenance" command from bottom panel or pop-out error window after error count message, e.g. error count message, button with tooltip

3 error(s) found in this validation. 
<img width="20" alt="screenshot 2018-03-17 04 12 10" src="https://user-images.githubusercontent.com/9379524/37537477-6bf57612-2999-11e8-9943-51e63c223313.png"> Write errors to Provenance Information

Rough but that's the general idea

**Comment by Stephen-Gates** [comment]
@mattredbox can this be closed?

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
I believe it works ok from the main window.
I'm not sure this quite works correctly from the separate Errors window, so either keep open or open a separate issue for this.
