### ISSUE TITLE
Scroll bars appear when hover over next column >

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#410]
### Current Behaviour (for problems)

<img width="444" alt="screenshot 2018-01-25 05 50 55" src="https://user-images.githubusercontent.com/9379524/35353789-09940312-0194-11e8-9981-86c89fcf5e7b.png">

When I hover over the next column arrow, the vertical and horizontal scroll bars appear and the table scroll bars disappear

### Expected Behaviour

The scroll bars remain on the table like this

<img width="671" alt="screenshot 2018-01-25 05 55 06" src="https://user-images.githubusercontent.com/9379524/35353925-661e1802-0194-11e8-8a5e-394f2e449cf1.png">

### Your Environment

* Data Curator version: 0.9.0 Develop
* Operating System and version: e.g. macOS High Sierra 10.13.2

**Comment by mattRedBox** [comment]
May be just peculiar to dev environment, but will check

**Comment by mattRedBox** [comment]
Nope it's in prod env too, will fix

**Comment by mattRedBox** [comment]
Ok it's the tooltip divs for the arrows.  Moving the position to left seems to fix, so will add to release.
