### ISSUE TITLE
Opening a Data Package that I just created fails gives an error message: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by pripley123** [ODIQueensland/data-curator#439]
Opening a Data Package that I just created fails gives an error message:
ENOENT: no such file or directory, open '<path>\<package name>\datapackage.json'

Workaround:
I found a workaround was to extract the Data Package zip first in the same folder as the zip.  Once I did that I was able to open the Data Package in Data Curator without error

### Current Behaviour (for problems)
> When reporting a problem, describe what happens that isn't expected behaviour?
 try to open the Data Package I just created I get the following error:
Import Data Package Error
ENOENT: no such file or directory, open '<path>\<package name>\datapackage.json'

### Expected Behaviour
> The Data Package should open without error

### Steps to Reproduce
> 
1. Open Data Curator using the icon
2. When I successfully export a Data Package and then close Data Curator open it back up and then
3. Try to open the Data Package I just created

### Your Environment
>Windows 10 Enterprise, version 1709
64 bit

* Data Curator version: 0.9

**Comment by Stephen-Gates** [comment]
@pripley123 Thanks for reporting this. It is possible to share the original file you were trying to open?

Did you have a .zip with inside:

|- datapackage.json
|- / data
|      |- data.csv

**Comment by pripley123** [comment]
here you go.


All the info you mentioned is in the zip

________________________________

**Comment by Stephen-Gates** [comment]
@pripley123 I don't think your .zip got posted in the comment above (or I'm blind as a bat!).

If your .zip isn't on the web, here's a great chance to add it to https://github.com/pripley123/myfirstrepo I can see from your profile that your new to GitHub so let me know if I can help, or you can email it to stephen [at] theodi.org.au

**Comment by pripley123** [comment]
ah, I see... I attached it to the email when I responded in outlook ... guess I need to attach files directly here (I edited previous comment to attach the file)

**Comment by Stephen-Gates** [comment]
@pripley123  I got the same error 

![open-data-package-zip-error](https://user-images.githubusercontent.com/9379524/35838942-933c5dae-0b39-11e8-962c-ac0de2c33e56.PNG)

Developer is on holidays at present. We'll pick this up late next week.

**Comment by pripley123** [comment]
Sounds good.  Thanks.

**Comment by Stephen-Gates** [comment]
@mattRedBox forgot to mention this today. This was working. Any clues?

**Comment by Stephen-Gates** [comment]
See also #304

**Comment by mattRedBox** [comment]
Will be in upcoming release.
