### ISSUE TITLE
Pin close button to the top right on the validation errors panel

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#448]
### Current Behaviour (for problems)

Close button scrolls

<img width="781" alt="screenshot 2018-02-10 15 25 16" src="https://user-images.githubusercontent.com/9379524/36058861-418bb482-0e77-11e8-899b-b77caac9c2b7.png">

<img width="798" alt="screenshot 2018-02-10 15 25 28" src="https://user-images.githubusercontent.com/9379524/36058862-41eda21e-0e77-11e8-96c4-69aabb935c2e.png">

### Expected Behaviour

Close button is fixed top right

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version: 0.9.0
* Operating System and version: e.g. macOS High Sierra 10.13.3

**Comment by Stephen-Gates** [comment]
Close scrolls off panel with errors

<img width="805" alt="screenshot 2018-03-21 19 57 49" src="https://user-images.githubusercontent.com/9379524/37703680-32b16cd8-2d42-11e8-9c70-ce488267a762.png">

**Comment by mattRedBox** [comment]
Creating a fixed header in bottom panel, including close icon will take some time. There's a lot of css now to deal with fixed/absolute/relative position to handle various scrollbars and headers - unfortunately not as simple as it was for navbar. Won't make it in this release.

**Comment by Stephen-Gates** [comment]
Problem remains in 0.17.0

**Comment by Stephen-Gates** [comment]
Fixed 👍 

<img width="802" alt="screenshot 2018-06-21 17 39 29" src="https://user-images.githubusercontent.com/9379524/41704638-234537c2-757a-11e8-9425-461fa03fbadb.png">
