### ISSUE TITLE
Set caseSensitiveHeader = true in dialect?

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#464]
### Current Behaviour (for problems)

I can create a column named `a` and another called `a` and this correctly fails validation.

I can create a column named `a` and another called `A` and this passes validation.

Given these are treated as different, I think the [`caseSensitiveHeader`](https://frictionlessdata.io/specs/csv-dialect/#specification)  should =` true`

### Expected Behaviour

In `dialect`: 
```
"caseSensitiveHeader": "true"
```

### Your Environment

* Data Curator version: 0.10.0 dev
* Operating System and version: macOS High Sierra 10.13.3

**Comment by Stephen-Gates** [comment]
But given the wording at https://frictionlessdata.io/specs/table-schema/#name perhaps it would be better to force all column names to lower-case and set `"caseSensitiveHeader": "false"
`.

Thoughts?

**Comment by louisjasek** [comment]
Theoretically it makes sense to make it not case sensitive - and force lower case. I would be all for this approach.

But before we go ahead, do you see any practical reasons for not doing this ? Do you know if this situation comes up much? And if so, do you think we would be making it difficult by enforcing this standard?

**Comment by Stephen-Gates** [comment]
I would only be guessing but I can't imagine people having the same column names with the only difference being case. You could do some analysis in CKAN if you want to be certain (e.g. [What is a CSV? A case study of CSVs on data.gov.uk](https://theodi.org/blog/the-status-of-csvs-on-datagovuk))

**Comment by Stephen-Gates** [comment]
@louisjasek I propose:

- converting Column Name to lower-case
- pre-filling Column Title with the actual case
- setting the CSV dialect to  "caseSensitiveHeader": "false" 

@mattRedBox any concerns?

**Comment by mattRedBox** [comment]
I'd be reluctant to force a setting like that (ie: make everything lowercase), unless we introduce a setting later that allows user to choose - especially if we're moving data back and forth between Data-Curator and other apps, and trying to follow frictionless standard with everything else. I'll check with frictionless datapackage-js to see if 'caseSensitiveHeader' is supported in validation. At the moment, the default is false but I'm not sure if it's used anywhere

**Comment by mattRedBox** [comment]
caseSensitiveHeader : false
Put menu item under Tools->Header Row : to change this setting
Put in check for this setting when we check whether header names are present in validation
(check also what happens on frictionless side).
