### ISSUE TITLE
Multiple missing values not writing correct datapackage.json

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#467]
### Current Behaviour

I have a table with missing values represented by "TBA" and null ""

I specify missing values (tried with `" "` and `""`)

![missing](https://user-images.githubusercontent.com/9379524/36243240-44f5152a-126c-11e8-8492-3dbe1feb8edc.PNG)

Validation doesn't work

![missing3](https://user-images.githubusercontent.com/9379524/36243294-98feadde-126c-11e8-812a-406118712812.PNG)

datapackage.json written as 

![missing2](https://user-images.githubusercontent.com/9379524/36243256-60cac042-126c-11e8-8e75-616453d44ba3.PNG)

### Expected Behaviour

Validation works with multiple missing values

Datapackage.json converts `""` to `""` not `" \"\"`

### Your Environment

* Data Curator version: 0.10.0
* Operating System and version: Windows 7

**Comment by Stephen-Gates** [comment]
This should work...

<img width="1014" alt="screenshot 2018-03-12 20 38 07" src="https://user-images.githubusercontent.com/9379524/37279072-6865705e-2635-11e8-9088-23a8686871e2.png">

See also https://github.com/frictionlessdata/specs/pull/588

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates,
Put in the values without quotes

**Comment by Stephen-Gates** [comment]
Fixed 

<img width="782" alt="screenshot 2018-03-24 16 30 15" src="https://user-images.githubusercontent.com/9379524/37861222-af64dd10-2f80-11e8-8fc4-199693967438.png">
