### ISSUE TITLE
Improve unique constraint validation error message

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#475]
The unique constraint validation is working 🎉 

### Current  Behaviour (for feature requests only)
<img width="604" alt="screenshot 2018-02-17 10 26 20" src="https://user-images.githubusercontent.com/9379524/36335665-52749c54-13cd-11e8-8f8d-dd264c429f6f.png">

### Expected Behaviour

Instead of: 
`(column:N/A) Row 2 has an unique constraint violation in column "ab"`

Something like:

`Column "ab" Row 2 violates the unique constraint`

### Your Environment

* Data Curator version: 0.10.0
* Operating System and version:  macOS High Sierra 10.13.3

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
I can take care of the display of (column: N/A) - I originally put this here when you were testing which errors were/weren't reporting column numbers.
But that message format comes from frictionless - could you raise it with them - to be sure it is the way you would like it displayed?

**Comment by Stephen-Gates** [comment]
Error message is now 

<img width="456" alt="screenshot 2018-04-01 14 42 29" src="https://user-images.githubusercontent.com/9379524/38169918-f44e0470-35ba-11e8-9f96-03d5f3149cd8.png">
