### ISSUE TITLE
Last column is not being validated for unique constraint

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#476]
### Current Behaviour 

Last column is not being validated for unique constraint

<img width="842" alt="screenshot 2018-02-17 10 38 42" src="https://user-images.githubusercontent.com/9379524/36335858-d8235a7e-13ce-11e8-8a58-f8d05ba66f23.png">

### Expected Behaviour
Last column is validated against the unique constraint

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version: 0.10.0
* Operating System and version:  macOS High Sierra 10.13.3

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
This is because of the way frictionless is only able to collect 1 unique constraint violation for the relevant rows at a time. If you fix the first violation in the same row, you should find that the other column unique constraint violation, of put the final column violation in their own row to test. Not sure if this is worth asking to fix, as, like in other parts of the application, other violations reveal themselves once others are taken care of.

**Comment by Stephen-Gates** [comment]
@louisjasek are you ok to close? Fixing requires changes to external software library.

**Comment by louisjasek** [comment]
@Stephen-Gates does this mean the unique constraint validator does not work for the last column in any CSV?

What is the best approach to fix this in the longer term? I note that @mattRedBox mentions it may not be worth asking to fix the external software library.

**Comment by Stephen-Gates** [comment]
@louisjasek No. I think what @mattRedBox is saying that the validation only processes 1 unique constraint per row so after fixing the initial unique constraint error and validating again, you may get another unique constraint constraint error for that row

**Comment by mattRedBox** [comment]
Correct, you will

**Comment by louisjasek** [comment]
Ah I see. And do you have a perspective on the best approach or options to fix this in the longer term?

**Comment by Stephen-Gates** [comment]
I don't think it's a bug. The external validation library doesn't test every error otherwise processing would take too long. So validate, fix reported errors, validate, fix reported errors, until valid. 

I believe this is only an issue with multiple unique constraints which probably isn't common.

@mattRedBox is that correct? If so then I think we can resolve by adding a known issue on https://ask.theodi.org.au/c/projects/data-curator and then close this issue.

**Comment by Stephen-Gates** [comment]
Issue will be documented at 

https://ask.theodi.org.au/t/known-issue-validation-only-checks-one-unique-constraint-per-row/534

**Comment by Stephen-Gates** [comment]
@louisjasek any objections to closing this issue?

**Comment by louisjasek** [comment]
@Stephen-Gates fine to close. We have it documented on the ODI forum. Do we need to leave it as an issue in github as well? Even if it isn't allocated to one of our milestones? Let me know know your thoughts.

**Comment by Stephen-Gates** [comment]
We’ll pick up

**Comment by Stephen-Gates** [comment]
Whoops- we’ll pick improvements as we update dependencies
