### ISSUE TITLE
Design icon for project

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#5]
Needs to work across macOS, Windows 7, 8, 10, Linux

**Comment by Stephen-Gates** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Identity - Name, Icon, etc](https://trello.com/c/JaUn6R3u/25-identity-name-icon-etc)

**Comment by Stephen-Gates** [comment]
Words to inspire: **Data Curator** is a simple desktop CSV editor to help **describe**, **validate** and **share** **usable open data**

Other words that may trigger ideas
- package
- [frictionless data](https://discuss.okfn.org/t/frictionless-data-branding/5460) (image)

**Comment by Stephen-Gates** [comment]
Why this?
- hexagon and green relates to the [ODI skills framework](https://theodi.org/open-data-skills-framework)
- the box shape relates to data packages
- the gift wrapping relates to the applications purpose - sharing usable open data

![data-curator-icon-2](https://user-images.githubusercontent.com/9379524/28993329-01943dc8-79f7-11e7-922e-d5e0af34bd02.png)

**Comment by pezholio** [comment]
Oooh, nice! Make sure the size of the sticker is complaint with the [hexagon sticker standard](https://github.com/terinjokes/StickerConstructorSpec) though 😄

**Comment by Stephen-Gates** [comment]
Will do 👍🏼 But the skills framework icons will need to rotate to comply 🙀

Icon in context

<img width="886" alt="screenshot 2017-08-06 20 06 00" src="https://user-images.githubusercontent.com/9379524/29006273-0375255a-7b30-11e7-828b-4e2098bc9ee7.png">

**Comment by Stephen-Gates** [comment]
Some people have suggested having a defined edge on the package. 
Others like the original. Here's an alternative for consideration. 

![data-curator-facet-256](https://user-images.githubusercontent.com/9379524/29048453-f6f03eb6-7c13-11e7-8d51-7af11f27e715.png)

**Comment by Stephen-Gates** [comment]
Going with the first option
