### ISSUE TITLE
Acceptance Test writing level

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#595]
I've been cleaning up the [Edit acceptance tests](https://github.com/ODIQueensland/data-curator/tree/develop/test/features/edit). I've written them at a high level (e.g. [insert row above](https://github.com/ODIQueensland/data-curator/blob/develop/test/features/edit/insert-row-above.feature)) and @mattRedBox has written them at a low level (e.g. [insert row below](https://github.com/ODIQueensland/data-curator/blob/develop/test/features/edit/insert-row-below.feature)). 

We need to agree a level that both works as user documentation and supports automated testing. 

It seems that high level tests can be automated looking at [cucumber pro documentation](https://app.cucumber.pro/projects/cucumber-pro/documents/branch/master/features/publish_and_read/publish_documentation.feature#rules) (Matt I've sent an invite)

**Comment by Stephen-Gates** [comment]
E.g. Do we need 

> Given Data Curator is open

in every test?

**Comment by Stephen-Gates** [comment]
Did a big clean up of tests to finalise the move to Cucumber Pro. Things to note:

- you can use [underline method for markup headings](http://commonmark.org/help/
) in feature descriptions
- there are [Cucumber anti-patterns](https://cucumber.io/blog/2016/07/01/cucumber-antipatterns-part-one) including "Scenarios that use 'I' as in the personal pronoun" which I have addressed
- you can choose a branch to view
- you can have a discussion about an individual line in the feature
- [Cucumber Pro public roadmap](https://trello.com/b/IF4UTQac/cucumber-pro-public-story-map) shows new features - vote for your favourites

<img width="953" alt="screenshot 2018-03-25 17 47 10" src="https://user-images.githubusercontent.com/9379524/37872923-9b8286ce-3054-11e8-8e69-5cdc7941a40d.png">

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
The tests steps I've added are necessary to cue the actual mechanics of the underlying framework to step through the tests.

As/If I get more time to work on them, with common behaviour, then yes I can abstract these away into a higher level feature that can be used.
And in regards to questions like:
_Given Data Curator is open_
then yes these too can be moved into what are known as common 'background' mechanics that can operate across multiple tests.

However I think there isn't much that needs to be done - as you are engaging these at a high level, continue to write these at that level. As I interact with these, if more specifics are needed to cue test mechanics then I need to add these  - but with time and common behaviours I can abstract them back into something higher level. But not without being allocated time for these within sprints.
