### ISSUE TITLE
Keyboard Shortcuts don't display on Windows 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#60]
### Expected Behaviour
https://relishapp.com/odi-australia/data-curator/docs/help/initiate-an-edit-feature-using-a-keyboard-shortcut

### Current Behaviour (for problems)
![no-shortcuts](https://user-images.githubusercontent.com/9379524/30196745-50416922-94a6-11e7-8841-faf6fb73dd4b.PNG)

### Steps to Reproduce (for problems)

1. Select Keyboard Shortcuts menu item

### Your Environment

* Data Curator: 0.2.3
* Operating System:  Windows 7

**Comment by Stephen-Gates** [comment]
Error remains on Windows 7, Data Curator 0.3.1

**Comment by Stephen-Gates** [comment]
Issue remains on Windows 7, Data Curator 0.3.4
![image](https://user-images.githubusercontent.com/9379524/31157511-e176c7cc-a8fe-11e7-9c3b-e91d7d6878e4.png)

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
I've seen another ticket like this (about opening excel file).
I notice that on the Windows 7 machine I have here that things run very slow.
Any chance you're not waiting long enough (say 20s or more for screen to appear).

See this comment which may/may not be relevant:
https://stackoverflow.com/questions/39648969/node-js-electron-applications-for-single-core-windows-7-machines-are-slow-on-file%20I/O

**Comment by Stephen-Gates** [comment]
@mattRedBox waited more than 20s but problem remains in 0.3.5

![image](https://user-images.githubusercontent.com/9379524/31262317-837f9e28-aa9d-11e7-8204-3f58191c471c.png)

**Comment by Stephen-Gates** [comment]
Related to #78
