### ISSUE TITLE
Save as error

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#605]
### Current Behaviour 

Save as returns

<img width="618" alt="screenshot 2018-03-27 21 07 05" src="https://user-images.githubusercontent.com/9379524/37963859-e82fa3d0-3202-11e8-816d-db80d2f0e059.png">

### Steps to Reproduce

1. Open Data Curator using the icon
2. Enter data
3. Save as

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version: 0.13.0 dev
* Operating System and version:  macOS High Sierra 10.13.3

**Comment by mattRedBox** [comment]
Fixed - probably better that master is tested against, rather than develop branch.

**Comment by Stephen-Gates** [comment]
Fixed 🎉
