### ISSUE TITLE
Quit doesn't quit

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#616]
### Current Behaviour (for problems)

1. open data curator
2. quit
3. OK quit
4. Application remains open

### Expected Behaviour
1. open data curator
2. quit
3. OK quit
4. Application quits

### Your Environment
.

* Data Curator version: 0.13.0
* Operating System and version: macOS High Sierra 10.13.3

**Comment by pripley123** [comment]
+1 for this.  It's annoying when I have to go into Task Manager to close the application (when I close Data Curator and then try to open again via the icon, I see a flash and then it doesn't open... it only works again when I kill it in Task Manager)

**Comment by Stephen-Gates** [comment]
@pripley123 this should be fixed in the next release later this week

**Comment by pripley123** [comment]
Great to hear it's getting fix.  Thanks for letting me know.

________________________________

**Comment by mattRedBox** [comment]
Fixed in release 0.14.0.

**Comment by louisjasek** [comment]
Works for me now!
