### ISSUE TITLE
Open file using Drag and Drop

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#63]
### Desired Behaviour 

Drag a file on to Data Curator to open it

[Acceptance test](https://app.cucumber.pro/projects/data-curator/documents/branch/develop/test/features/other/open-file-using-drag-n-drop.feature) 

###  Resources

- https://electron.atom.io/docs/api/file-object/ 
- https://ourcodeworld.com/articles/read/288/how-to-handle-drag-and-drop-file-feature-in-electron-framework
- https://gist.github.com/dcposch/1e546279f162de7d644b224058b27fb0#file-electron-drag-drop
- use CSV sniffer to determine dialect https://www.npmjs.com/package/csv-sniffer

<img width="567" alt="screenshot 2017-09-09 05 32 35" src="https://user-images.githubusercontent.com/9379524/30228294-67a66336-9520-11e7-8693-3a6d23d0ea41.png">

**Comment by mattRedBox** [comment]
Re-tested. Drag and drop supported.
