### ISSUE TITLE
Column Property panel preventing entry of some values

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#632]
### Current Behaviour 

Some column properties cannot be entered, e.g.

- any non-default format
- all Constraints

### Steps to Reproduce

1. Open Data Curator using the icon
2. enter some data
3. guess
4. change a type to date 
5. try pick a format - error

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version: 0.13.0
* Operating System and version:  macOS High Sierra 10.13.4

**Comment by Stephen-Gates** [comment]
@mattRedBox this is preventing any meaningful use of the App

**Comment by Stephen-Gates** [comment]
Thanks @mattRedBox will test this afternoon

**Comment by mattRedBox** [comment]
@Stephen-Gates 
If you think this requires the equivalent of hot fix - release of 13.1 let me know and I'll tag and release this today

**Comment by Stephen-Gates** [comment]
@mattRedBox I think that would be good given https://github.com/ODIQueensland/data-curator/issues/611

**Comment by mattRedBox** [comment]
Release v0.13.1

**Comment by louisjasek** [comment]
Works for me, recreating your steps @Stephen-Gates
