### ISSUE TITLE
Find next/previous in table/column 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#633]
### Desired Behaviour 

Find next/previous search values across a table or within a column

[Acceptance test](https://app.cucumber.pro/projects/data-curator/documents/branch/develop/test/features/find/find.feature)

<img width="938" alt="screenshot 2018-04-01 07 25 30" src="https://user-images.githubusercontent.com/9379524/38167738-0308cf50-357e-11e8-9c9d-a5dae68e9e7c.png">

Replaces #81

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
The acceptance test mentions 'highlight'.
What should this look like (e.g., what colour, background, border)?

**Comment by Stephen-Gates** [comment]
@mattRedBox Excel does a green surround on the current found item

<img width="160" alt="screenshot 2018-04-03 14 14 24" src="https://user-images.githubusercontent.com/9379524/38228968-95c7c9a0-3749-11e8-9453-1e5c6ac28834.png">

You could try a green background on all found items

IKIWISI ;-)

**Comment by mattRedBox** [comment]
Not sure we can release this yet - still haven't solved performance issue - also an issue for find by column - hot can't keep up with selecting cells in iterating through column at a time either.

**Comment by Stephen-Gates** [comment]
Thanks for reporting @mattRedBox

**Comment by Stephen-Gates** [comment]
@mattRedBox support on https://forum.handsontable.com is really responsive - worth considering

**Comment by louisjasek** [comment]
@mattRedBox how are you going with this? I have testing scheduled for tomorrow - wondering whether I should keep this in my calendar or not.

**Comment by Stephen-Gates** [comment]
We should have a build out tonight

**Comment by mattRedBox** [comment]
Just in column for now - in table can be added now with minimal effort.

**Comment by louisjasek** [comment]
Majority of this working as expected. But I found a minor issue with highlighting. Once you have finished finding next in one column, and move to another column, some of the highlights in the previous column you were working on remain.

Steps to reproduce
- Select a column
- Enter value in 'Find in column' field that matches text in the column and press next a few times
- Select a different column
- Enter value in 'Find in column' field that matches text in the column and press next a few times

See attached for picture showing highlights in multiple columns after following these steps -

![screen shot 2018-04-19 at 7 58 12 am](https://user-images.githubusercontent.com/36529635/38960796-41f91fce-43a9-11e8-97e7-463e87d592d7.png)

Environment details:
- macOS Sierra 10.12.6
- DataCurator 0.14.0

**Comment by Stephen-Gates** [comment]
Thanks for reporting this @louisjasek. To help with managing issues can you please a separate issue for this so it can be added to another milestone? Just type #633 to refer back to this issue

**Comment by louisjasek** [comment]
done @Stephen-Gates see issue #708
