### ISSUE TITLE
Replace next/all across a table or within a column

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#634]
### Desired Behaviour 

Replace next/all across a table or within a column

[Acceptance test](https://app.cucumber.pro/projects/data-curator/documents/branch/develop/test/features/find/replace.feature)

<img width="938" alt="screenshot 2018-04-01 07 25 30" src="https://user-images.githubusercontent.com/9379524/38167738-0308cf50-357e-11e8-9c9d-a5dae68e9e7c.png">

Replaces #81

**Comment by Stephen-Gates** [comment]
In Excel the result is... 

<img width="198" alt="screenshot 2018-04-10 19 52 41" src="https://user-images.githubusercontent.com/9379524/38550056-ce725978-3cf8-11e8-9b35-2412ba246516.png">

...so let's go with that

**Comment by mattRedBox** [comment]
Just in column for now - in table can be added now with minimal effort.

**Comment by louisjasek** [comment]
Created new issue #709 to cover the above @Stephen-Gates @mattRedBox
