### ISSUE TITLE
Error opening datapackage.zip - license missing

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#638]
### Current Behaviour 

Tried to open local copy of https://github.com/frictionlessdata/example-data-packages/blob/master/zip/periodic-table.zip and got 

<img width="998" alt="screenshot 2018-04-02 08 49 25" src="https://user-images.githubusercontent.com/9379524/38178303-2290dfe0-3653-11e8-98fa-5f9a4bd1c610.png">

### Expected Behaviour

Data package opens

### Steps to Reproduce

1. Open Data Curator using the icon
2. Open Data Package...
3. Choose file > error

### Your Environment

* Data Curator version: 0.13.0
* Operating System and version:  macOS High Sierra 10.13.4

**Comment by Stephen-Gates** [comment]
Data was is error

**Comment by Stephen-Gates** [comment]
/remind me to fix the zip file on 24 May

**Comment by Stephen-Gates** [comment]
Fixed zip but error persists when I open locally or from url 

using https://github.com/frictionlessdata/example-data-packages/blob/master/zip/periodic-table.zip I got:

<img width="792" alt="screenshot 2018-05-27 14 06 23" src="https://user-images.githubusercontent.com/9379524/40582368-3625c3b0-61b7-11e8-90ef-9c405ab6f8ab.png">

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Mac zips/unzips creates a __MACOSX folder (something to do with resource forking) which we don't need, so will eliminate this from import unpacking.

**Comment by Stephen-Gates** [comment]
thanks @mattRedBox

**Comment by Stephen-Gates** [comment]
fixed in 0.18.0
<img width="788" alt="screenshot 2018-06-05 23 17 13" src="https://user-images.githubusercontent.com/9379524/40978302-a5a14c6c-6916-11e8-9955-4d16cca67802.png">

However package licence not imported
<img width="792" alt="screenshot 2018-06-05 23 20 16" src="https://user-images.githubusercontent.com/9379524/40978517-2bdfd4ba-6917-11e8-8ba0-f2021e7b2148.png">
