### ISSUE TITLE
First time Save doesn't prompt for filename and locations

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#64]
### Expected Behaviour
https://relishapp.com/odi-australia/data-curator/docs/file/save

### Current Behaviour (for problems)
First time Save doesn't prompt for filename and locations

### Steps to Reproduce (for problems)

1. Enter data
2. Select Save menu item
3. No prompt presented
4. Unclear if file was saved and if so, where

### Your Environment

* Data Curator 0.2.3
* Operating System macOS Seirra 10.12.6

**Comment by albreez** [comment]
I would like to see a status bar or something for this, where the user can see what operations the program is performing, such as saving a file or processing. Most applications have this at the bottom of the screen.

**Comment by Stephen-Gates** [comment]
@albreez good idea. 

Would you mind creating a separate feature request for this please?
There are some very cool [loading](https://codepen.io/kjbrum/pen/BraCg) [indicators](https://codepen.io/martinvd/pen/xbQJom) out there.

**Comment by Stephen-Gates** [comment]
Fixed on windows
