### ISSUE TITLE
Data Package version number error message out of place

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#640]
### Current Behaviour 

<img width="401" alt="screenshot 2018-04-02 20 05 59" src="https://user-images.githubusercontent.com/9379524/38192685-673d1448-36b1-11e8-83e8-39f19dae01dd.png">

### Expected Behaviour

Erro message displayed under property 

### Your Environment

* Data Curator version: 0.13.0
* Operating System and version:  macOS High Sierra 10.13.4

**Comment by mattRedBox** [comment]
This seems to have been there for a while - will try to fit in with upcoming releases.

**Comment by Stephen-Gates** [comment]
Problem remains in 0.17.0

**Comment by mattRedBox** [comment]
Looks like block for validation feedback is showing all css out of place.

**Comment by Stephen-Gates** [comment]
Fixed 
<img width="375" alt="screenshot 2018-06-24 09 32 03" src="https://user-images.githubusercontent.com/9379524/41814496-8d3acf2a-7791-11e8-88bc-c8b7ea33b1da.png">
