### ISSUE TITLE
Cannot enter constraints

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#645]
### Current Behaviour 
Cannot enter constraints in column properties 

As soon as I type a value, the input box closes

### Expected Behaviour

can enter constraints

### Your Environment

* Data Curator version: 0.13.1
* Operating System and version: e.g. macOS High Sierra 10.13.4

**Comment by mattRedBox** [comment]
Will hotfix this for 0.13.2

**Comment by mattRedBox** [comment]
Fixed. Added our own highlight now, instead of trying to overwrite hot's select/deselect. Should fix all of these associated errors.

**Comment by Stephen-Gates** [comment]
Fixed :tada: 

Thanks for all your efforts @mattRedBox - very much appreciated 😄
