### ISSUE TITLE
Provide feedback for user about loading validation feedback from large datasets

### ISSUE THREAD

**Issue by mattRedBox** [ODIQueensland/data-curator#650]
Please see : #611 
`When I select minConstraints, I do seem to get some errors feedback that I wasn't expecting (but not necessarily the errors you're seeing) - not sure yet if there's a problem on our side or something up with data yet. However, what I do notice is the lag for large datasets between selecting 'Validate' and when the messages actually return (the larger the dataset, the longer the messages take to appear). We could perhaps use the loading screen wait message here (faster for effort than trying to do something asynchronous with streaming back errors 1 at a time at this stage I think) - as this may also cause issues for users when old validation messages don't refresh quickly enough.`

**Comment by Stephen-Gates** [comment]
Agreed reuse loading screen first. 
Can add a realistic progress bar or stream error messages later

**Comment by Stephen-Gates** [comment]
I think this is done 
<img width="1440" alt="screenshot 2018-06-12 23 27 04" src="https://user-images.githubusercontent.com/9379524/41293253-25837cda-6e98-11e8-8518-3156a6a85169.png">
