### ISSUE TITLE
Writing validation errors to provenance information overwrites previous written errors

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#654]
If I have a data package with two tables, both with errors and I want to append both sets of errors to the provenance information, I can't do that as writing errors to provenance overwrites any prior errors written.

Not sure on the best way to handle this - suggestions welcome

**Comment by Stephen-Gates** [comment]
Perhaps...

![provenance-errors-2](https://user-images.githubusercontent.com/9379524/38391459-9dc8ba5e-3967-11e8-80c9-d504d56dea2d.png)

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
That seems fine to me.
