### ISSUE TITLE
Investigate problem raised with datetime or min constraints

### ISSUE THREAD

**Issue by mattRedBox** [ODIQueensland/data-curator#669]
See Issue 1. raised in #611 
Summary

@louisjasek:
`I can't get the time pattern constraint to work. I have a a dataset with a column where time values should be HH:MM (not all are - but I am setting this as the property as I want to fix values where they do not conform to this). When the column is set to type time and format as pattern (%H:%M) it throws the error 'the value "[TIME VALUE]" does not conform to the 'minLength' constraint for column" [Column]"'. When the columns is set to type time and format as default it throws the error 'The value "[Time Value]" in column "[Column]" is not type "time" and format "default". Is this time (e.g. '20:00') really not in the right format? To me that is the correct format?) See screenshots below. Data is here: https://data.qld.gov.au/dataset/fireworks. Also different but related - is there an easy way of linking to information about the date and time patterns that we support from the UI? If you select pattern it just gives you a blank box. I had to search through our git repository to find which ones are supported - it took me a while to figure it out.`

@mattRedBox:
When I select minConstraints, I do seem to get some errors feedback that I wasn't expecting (but not necessarily the errors you're seeing) - not sure yet if there's a problem on our side or something up with data yet. However, what I do notice is the lag for large datasets between selecting 'Validate' and when the messages actually return (the larger the dataset, the longer the messages take to appear). We could perhaps use the loading screen wait message here (faster for effort than trying to do something asynchronous with streaming back errors 1 at a time at this stage I think) - as this may also cause issues for users when old validation messages don't refresh quickly enough.

**Comment by Stephen-Gates** [comment]
Using the fireworks data, when I guess column properties the right pattern is guessed and is validated correctly

<img width="796" alt="screenshot 2018-05-27 13 39 19" src="https://user-images.githubusercontent.com/9379524/40582273-fedac0c0-61b3-11e8-8aad-19f799da28bb.png">

This is different to what was [previously experienced](https://github.com/ODIQueensland/data-curator/issues/611#issuecomment-378777024).

Closing - please reopen if the error can be reproduced.
