### ISSUE TITLE
maxLength constraint on string column gives error when trying to export 

### ISSUE THREAD

**Issue by pripley123** [ODIQueensland/data-curator#673]
When I add a maxLength constraint for a string column and then try to export the data package I get an error:
"There is a required table or column property that is missing.  Please check that all required properties are entered"

To test that it's the constraint that's the issue, I clicked the "Export" button and it showed the save dialog (indicating success).  Then I added the constraint of maxLength with a value of 50.  Then I tried to export and was presented with the above error message.  Then I removed the constraint.  The export worked.

### Expected Behaviour
Adding maxLength constraints does not prevent me from exporting the data package

### Steps to Reproduce
1. Open Data Curator using the icon
2. import a data package
3. pick a field that is a string
4. add a maxLength constraint of 50
5. Click the Export button

### Your Environment

* Data Curator version: 0.13.2
* Operating System and version: Windows 10 Enterprise, version 1709, OS build 16299.309

**Comment by Stephen-Gates** [comment]
Was able to reproduce this error

<img width="968" alt="screenshot 2018-04-12 06 15 22" src="https://user-images.githubusercontent.com/9379524/38640914-f63ef6fc-3e18-11e8-8c5f-127f1c0a5d7e.png">

**Comment by mattRedBox** [comment]
@Stephen-Gates 
The export fails as the validation in datapackage-js library expects a number, but the app passes a string for 'maxconstraint' = 3.
It's odd however, as validation with tableschema-js works correctly. I'll have a look at where the difference is occuring.

**Comment by mattRedBox** [comment]
Easier to fix on our side as the constraint should be a number, not a string anyway.

**Comment by Stephen-Gates** [comment]
Fixed in 0.18.0

<img width="1332" alt="screenshot 2018-06-05 23 05 53" src="https://user-images.githubusercontent.com/9379524/40977723-1ffa582a-6915-11e8-81e5-26d886e3dd77.png">
