### ISSUE TITLE
xls file loading failed: result only 1 row

### ISSUE THREAD

**Issue by 4estone** [ODIQueensland/data-curator#686]
### Current Behaviour
> When opening one xls or xlsx file with n rows result only one

### Expected Behaviour
> Loaded file should contained n rows like original sheet

### Steps to Reproduce
> When reporting a problem, provide a set of steps so others can reproduce the problem.

### Your Environment

* Data Curator version: 0.13.2
* Operating System and version: 
 Windows 10 64bit
[reseaux_201804.xlsx](https://github.com/ODIQueensland/data-curator/files/1915986/reseaux_201804.xlsx)

**Comment by Stephen-Gates** [comment]
Thanks for reporting this @4estone 😄 

I got the following when trying to reproduce this.

Excel with one row of data 

<img width="729" alt="screenshot 2018-04-17 05 46 10" src="https://user-images.githubusercontent.com/9379524/38831621-50f7e994-4203-11e8-9a1a-3db061164cf8.png">

opened in Data Curator

<img width="423" alt="screenshot 2018-04-17 05 46 55" src="https://user-images.githubusercontent.com/9379524/38831637-5d5c0012-4203-11e8-9723-02fd982e19a0.png">

Excel with four rows of data 

<img width="717" alt="screenshot 2018-04-17 05 49 09" src="https://user-images.githubusercontent.com/9379524/38831666-6fe37274-4203-11e8-9b7a-88062516e417.png">

Opened in Data Curator

<img width="827" alt="screenshot 2018-04-17 05 49 39" src="https://user-images.githubusercontent.com/9379524/38831680-7ccea648-4203-11e8-8345-549e98a659c2.png">

@louisjasek @mattRedBox I've placed this in milestone v0.18.0 but do you think this should/can be done earlier?

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
There's a problem here with not reading different line terminators. I can fix this quickly for next release.

**Comment by mattRedBox** [comment]
The only caveat here (to stay with behaviour that we were always doing):
any file opened, created,read is saved with the default line terminator (from frictionless), which atm is '\r\n'
So the excel sheets (open with line terminator of '\n') will be updated on save/export to '\r\n'

**Comment by Stephen-Gates** [comment]
That seems fine as we only save to CSV files and done provide a choice of line terminator

**Comment by Stephen-Gates** [comment]
Fixed on macOS in [v0.14.0](https://github.com/ODIQueensland/data-curator/releases/tag/v0.14.0) 🎉
