### ISSUE TITLE
Loading xls file failed

### ISSUE THREAD

**Issue by 4estone** [ODIQueensland/data-curator#691]
### Current Behaviour (for problems)
When I load xls file with n rows, there's only one in Data-curator, all rows were merged into a single one.
Excel sheet name was not recognized too.

### Expected Behaviour
Rows number should be same in Data Curator than in Excel

### Steps to Reproduce

1. Open Data Curator using the icon
2. File - Open Excel Sheet
3. Select Excel file (link below)
[reseaux_201804.xlsx](https://github.com/ODIQueensland/data-curator/files/1918526/reseaux_201804.xlsx)

### Your Environment

* Data Curator version: 0.13.2
* Operating System and version: Windows10 64

**Comment by mattRedBox** [comment]
Seems related to #686.
Will be available in upcoming release.

**Comment by 4estone** [comment]
Cool!

Tnaks

**Comment by Stephen-Gates** [comment]
Fixed on macOS in [v0.14.0](https://github.com/ODIQueensland/data-curator/releases/tag/v0.14.0) 🎉 

@4estone please confirm it's working correctly for you on Windows - Thanks again 😄
