### ISSUE TITLE
Latin charset missing recognition

### ISSUE THREAD

**Issue by 4estone** [ODIQueensland/data-curator#692]
### Current Behaviour (for problems)
When loading csv file with latin char inside, char are not recognised

### Expected Behaviour
Latin charset should be recognised ;-)

### Steps to Reproduce

1. Open Data Curator using the icon
2. File - Open - Semi colon separated
![image](https://user-images.githubusercontent.com/36297033/38857391-6e982394-4229-11e8-8114-8ab5683c5b80.png)

[comcant.txt](https://github.com/ODIQueensland/data-curator/files/1918774/comcant.txt)
(I had to rename csv file to .txt to upload)

### Your Environment

* Data Curator version: 0.13.2
* Operating System and version: Windows 10

**Comment by 4estone** [comment]
I confirm, as you can see in screenshot below, accents appears in original csv file: 

![image](https://user-images.githubusercontent.com/36297033/38866350-ed8a1312-4240-11e8-83fe-e781f43f7245.png)

**Comment by Stephen-Gates** [comment]
Sorry I can't replicate the error

<img width="795" alt="screenshot 2018-04-17 21 54 37" src="https://user-images.githubusercontent.com/9379524/38868331-0297d980-428a-11e8-84a0-cbdef3d8ff53.png">

or as a header 

<img width="413" alt="screenshot 2018-04-17 21 56 40" src="https://user-images.githubusercontent.com/9379524/38868414-49087820-428a-11e8-8575-6e197673aa9b.png">

**Comment by 4estone** [comment]
Yep, it seems there's an encoding issue. I have to:
1- Save xlsx as text unicode file
2 - Open txt file into notepad 
3- Ensure encoding is set to utf8
4 - Replace all tab by semi-colon
5 - Save ac csv
A little bit boring ;-)
Do you have any shortest way?
By the way, I hope that with xls issue fixing, I could forget this way in many case.

**Comment by 4estone** [comment]
When I save as CSV I have only:
![image](https://user-images.githubusercontent.com/36297033/38876083-10effa72-425c-11e8-81d8-7fb47db498bc.png)


![image](https://user-images.githubusercontent.com/36297033/38876556-f9cc81c0-425c-11e8-8f35-ef1edf58ac06.png)

**Comment by Stephen-Gates** [comment]
Closing as this appears to be a data source issue. Please reopen if problem with Data Curator can be demonstrated
