### ISSUE TITLE
Could not start Data Curator 2nd time before kill background process from former session

### ISSUE THREAD

**Issue by 4estone** [ODIQueensland/data-curator#696]
### Current Behaviour (for problems)
After starting first time DC and quit I cannot start again.
Look at active process and found 2 Data Curator
Killed them
Can start DC

Application process

![image](https://user-images.githubusercontent.com/36297033/38937732-25eca2ae-4324-11e8-824b-4fe1ea65a946.png)

Background process I have to kill after Data Curator Quit

![image](https://user-images.githubusercontent.com/36297033/38937800-553abfe6-4324-11e8-9074-8084f079d8a3.png)

### Expected Behaviour
Start session without killing background process

### Steps to Reproduce
1. Open Data Curator using the icon
2. Quit Data Curator
3. Open Data Curator using the icon

### Your Environment
* Data Curator version: 0.13.2
* Operating System and version: windows 10

**Comment by Stephen-Gates** [comment]
V0.14.0 will be out today - the release is currently in draft. Please retest with v0.14.0 when available as this should be fixed

**Comment by Stephen-Gates** [comment]
@4estone [v0.14.0](https://github.com/ODIQueensland/data-curator/releases) ready for your testing

**Comment by 4estone** [comment]
0.14.0 fix issue
