### ISSUE TITLE
Find and Replace is not Case-sensitive

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#705]
@louisjasek Should Find and Replace be case-sensitive?

<img width="874" alt="screenshot 2018-04-19 06 43 01" src="https://user-images.githubusercontent.com/9379524/38957160-28e0ce4e-439d-11e8-9d92-24bcd064a355.png">

**Comment by louisjasek** [comment]
Ideally I think there should be an option to find either (e.g. a match case tick box / button)- as you might not know what case the value you are searching for is in. Atom has a 'match case' button which I think works well - see below. The default is case insensitive.

![screen shot 2018-04-19 at 8 55 45 am](https://user-images.githubusercontent.com/36529635/38962192-854cd7ba-43af-11e8-91a7-fb9718a2aa71.png)

**Comment by Stephen-Gates** [comment]
Find is not case sensitive
<img width="643" alt="Screenshot 2019-06-04 20 17 41" src="https://user-images.githubusercontent.com/9379524/58871809-0b42ee00-8706-11e9-856d-e96c6560fcc4.png">

Replace is case sensitive 

Note message says 2 replaced but only 1 value was replaced
<img width="640" alt="Screenshot 2019-06-04 20 18 33" src="https://user-images.githubusercontent.com/9379524/58871828-1564ec80-8706-11e9-802f-511dced2f847.png">

**Comment by mattRedBox** [comment]
Hi @markwheels 
I've looked at this and can fix the case sensitivity in replace, so that it matches Find.
I'll split out the separate enhancement mentioned to add a 'case-sensitive' toggle in this ticket, just to ensure that you do/don't want that above other issues in this milestone.
