### ISSUE TITLE
Excel file loading hang on

### ISSUE THREAD

**Issue by 4estone** [ODIQueensland/data-curator#723]
### Current Behaviour (for problems)
open xls file hang on

![image](https://user-images.githubusercontent.com/36297033/39307881-546c8a9a-4964-11e8-8699-5c2bc431d55c.png)

### Expected Behaviour
success when loading excel file

### Steps to Reproduce

1. Open Data Curator using the icon
2. File - Open EXcel sheet
3.  Choose sheet
4. Open sheet
5. Wait...
6. Abort cause too long

File used:
[LIST.xlsx](https://github.com/ODIQueensland/data-curator/files/1951334/LIST.xlsx)

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version: 0.14.0
* Operating System and version: windows10 64bits

**Comment by Stephen-Gates** [comment]
Could be related to https://github.com/ODIQueensland/data-curator/issues/651

**Comment by Stephen-Gates** [comment]
When I attempt to open LIST.xlsx, even though it has one tab "Globale", Data Curator shows, 

<img width="366" alt="screenshot 2018-04-27 06 39 48" src="https://user-images.githubusercontent.com/9379524/39330784-0b35ac9e-49e6-11e8-9660-e14ab2da8c39.png">

I also get the same "Loading Data, Please Wait" screen using Data Curator v0.15.0.

I'll investigate further.

**Comment by mattRedBox** [comment]
Hi @4estone @Stephen-Gates 
This is related to #651 
The different worksheets shown possibly have something to do with some of the random data that is in this workbook. When I copy and paste just the table data into a new workbook, just 1 worksheet shows.
The conversion from excel to csv relies on some default properties such as "double quotes" and carriage returns to try to determine where cell fields end and lines end. Unfortunately in the worksheet, there are numerous double quotes and also carriage returns within different cells. The conversion, once it strips away excel 'cells' then leaves carriage returns and tries to implement quotes for text.
@4estone, in 651 we will put in a dialog message that warns of possible problems with data - there may also be some options we can add to assist the library conversion to help it work out where to put fields and line ends (but this may or may not be possible), but at this stage quotes and line returns within excel fields interfere with conversion to csv.

**Comment by Stephen-Gates** [comment]
Thanks @mattRedBox 
@4estone I'll close this in favour of #651 - There's a reference from that issue back to this one.

**Comment by mattRedBox** [comment]
Hi @4estone please see #733

**Comment by 4estone** [comment]
First thanks for reactivity.
Copy / paste data from excel to data Curator is a good workaround

**Comment by Stephen-Gates** [comment]
Works well in 0.18.0
<img width="794" alt="screenshot 2018-06-05 23 12 29" src="https://user-images.githubusercontent.com/9379524/40978117-184bcbbc-6916-11e8-8773-4098285e92b7.png">
