### ISSUE TITLE
Is Fix Ragged Rows needed in the Menu?

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#73]
If ragged rows are checked on opening the file, and the only choices are:

- fix ragged rows - setting the number of columns to the maximum number of columns 
- setting the number of columns to the number of columns in the first row

Then is there any need to have Fix Ragged Rows in the menu?

<img width="765" alt="screenshot 2017-09-09 19 12 58" src="https://user-images.githubusercontent.com/9379524/30238838-ef8fe48a-9592-11e7-8e1f-07cb72405c10.png">

**Comment by Stephen-Gates** [comment]
Perhaps it's useful on Open Data Package?

**Comment by pezholio** [comment]
To be honest, I think fixing ragged rows should be done automatically, otherwise it's not a valid CSV. I can't think of a valid use case for a CSV having ragged rows anyway

**Comment by Stephen-Gates** [comment]
Thanks @pezholio
Automatic it is!
