### ISSUE TITLE
Consider excel to csv options which may allow for smarter conversions

### ISSUE THREAD

**Issue by mattRedBox** [ODIQueensland/data-curator#733]
Following #651 
consider any available options which might assist library in working out csv delimiters and line terminators, specifically where excel sheets may contain line terminators and quotes within cells.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates @4estone
Had a quick look at this and looks like the excel library we use, XLSX, is much better at converting to json than csv. We already handle json as well as csv data in our app, so will be easy to fit into next release. @4estone, I was able to import your worksheet without trouble - it could be that some quotes you had inserted or line breaks aren't always honoured, but at a quick glance it seems to do a reasonable job.

**Comment by mattRedBox** [comment]
@Stephen-Gates @louisjasek
only added this to milestone as it's a decent win for maybe 5 minutes work.

**Comment by Stephen-Gates** [comment]
Works well in 0.18.0
