### ISSUE TITLE
Validate table for min/max length constraint causes data curator to stall 

### ISSUE THREAD

**Issue by louisjasek** [ODIQueensland/data-curator#743]
### Current Behaviour (for problems)
> If I add a minimum or maximum length constraint on a column and validate the table, if there is an error my software stalls/pauses. To fix, I have to quite DataCurator and start again. 

### Expected Behaviour
> The validation should work and highlight the constraint violation

### Steps to Reproduce
1. open data curator
2. open a csv (I tested this across multiple CSVs and a data package)
3. guess column properties
4. in a string column, add a minimum and/or maximum constraint (make sure there is a value in the column that will fail the constraint)
5. click 'validate table'
6. Data curator stalls/pauses without a successful validation

### Your Environment
* Data Curator version: 0.15.0
* Operating System and version: MacOS Sierra 10.12.6

**Comment by mattRedBox** [comment]
@Stephen-Gates  We have other issues raised for max/min contraints already I think? Need to link these together.

**Comment by Stephen-Gates** [comment]
#669 I believe

**Comment by Stephen-Gates** [comment]
/remind me to ensure this error is repeatable for work to start on 23 May 2018

**Comment by Stephen-Gates** [comment]
Can not reproduce the error 

<img width="1099" alt="screenshot 2018-05-27 13 19 51" src="https://user-images.githubusercontent.com/9379524/40582176-b32bdb80-61b0-11e8-9864-798a327e5010.png">
