### ISSUE TITLE
Enable entry of groupChar for Number data type

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#745]
Enable entry of groupChar for [`number`](https://frictionlessdata.io/specs/table-schema/#number) data type.

See #374

**Comment by mattRedBox** [comment]
Add input text box showing default values, which user can change.
Ensure this is sent with validation,export, etc.
Put input box between type and format.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Not 100% sure yet, but I'm going to issue a ticket in frictionless as I think it doesn't allow space, " ", as a valid group Char separator - as far as I can tell the frictionless spec should allow it. Can still work on this ticket and close off, but what it might mean is that numbers with spaces will just be allowed through (even when the default is set which is nothing or "").

**Comment by mattRedBox** [comment]
Testing seems to confirm. Before I send this as issue to frictionless (and so I can get on with this sprint release), @Stephen-Gates , I've been looking at:
https://frictionlessdata.io/specs/table-schema/#number
https://www.w3.org/TR/xmlschema-2/#decimal
https://www.w3.org/TR/xmlschema-2/#rf-whiteSpace
From what I can see, number is an atomic type, so whitespace should apply (with property collapse)? But then it also says that number (decimal from W3 spec) is:
`finite-length sequence of decimal digits (#x30-#x39)`
I note also that frictionless departs from W3 spec a bit as it allows leading trailing zeros whereas W3spec doesn't, but insists there must be digit on either side of decimal char. 
Just thought I should check with you first, before putting pull request in.

**Comment by Stephen-Gates** [comment]
@mattRedBox I’d add an issue as well as a pr. You probably won’t get a reply until tonight and discussion may follow before pr is accepted. Is the pr just to support `space`? Alternatively we could propose non-space Character in spec but I like the idea of handling spaces often placed in phone numbers
