### ISSUE TITLE
Redo not functioning 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#75]
### Expected Behaviour
https://relishapp.com/odi-australia/data-curator/docs/edit/redo

### Current Behaviour 
After insert row above, when I invoke redo using menu item or shortcut, the action isn't redone.

### Your Environment

- Data Curator: 0.2.3
- Operating System macOS Seirra 10.12.6

**Comment by Stephen-Gates** [comment]
It seems redo undoes an undo but perhaps doesn't repeat the action
https://docs.handsontable.com/pro/1.13.1/UndoRedo.html#redo

Perhaps this is a definition issue rather than a bug?

**Comment by albreez** [comment]
Both redo and undo do not work when using the menu command. However the hotkeys ctrl+z and ctrl+y work.

**Comment by Stephen-Gates** [comment]
I'll re-write the feature to reflect the hand on table functionality

**Comment by Stephen-Gates** [comment]
Still need to wire up menu and shortcut to handsontable redo

**Comment by Stephen-Gates** [comment]
I have temporarily disabled the menu item in https://github.com/ODIQueensland/data-curator/commit/f6eb0fb8d8ba8eb3821cadf3f76f7bc3defcb6e4 so it's not a problem in the Beta. Will fix in future release.

**Comment by mattRedBox** [comment]
@Stephen-Gates 
As you figured, with functions in place, redo is an 'unwind' of undo only.
