### ISSUE TITLE
Open Excel File

### ISSUE THREAD

**Issue by albreez** [ODIQueensland/data-curator#78]
I clicked on File > Open Excel Sheet 
The program opened file explorer.
I selected the file I wanted to open (it was a .csv)
I was presented with a blank dialogue with no error message
![data curator error 1](https://user-images.githubusercontent.com/31878214/30310757-611a3b5c-97d5-11e7-84c3-f34fb8a3d5a0.JPG)

### Expected Behaviour
The file should either open or I get an error message 

### Current Behaviour (for problems)
See above

### Steps to Reproduce (for problems)
> Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. Include code to reproduce, if relevant.
1. I clicked on File > Open Excel Sheet 
2. The program opened file explorer.
3. I selected the file I wanted to open (it was a .csv)
4. I was presented with a blank dialogue with no error message

### Your Environment
Windows 7, version 0.2.3

@Stephen-Gates @mattRedBox

**Comment by Stephen-Gates** [comment]
I get the same behaviour when I try to open an Excel file.
Note the new dialogue box that is opened, cannot be closed.

**Comment by Stephen-Gates** [comment]
Behaviour still present in v0.3.0 on Windows 7

**Comment by Stephen-Gates** [comment]
Fixed on macOS

**Comment by Stephen-Gates** [comment]
Still broken on Windows 7, Data Curator 0.3.2

**Comment by mattRedBox** [comment]
Also replicated in Windows 10.

**Comment by Stephen-Gates** [comment]
Now getting an open file panel but can't select .xls
![image](https://user-images.githubusercontent.com/9379524/30996269-fbee73ac-a502-11e7-8958-688328a5977e.png)

Windows 7, Data Curator 0.3.2

**Comment by Stephen-Gates** [comment]
reappeard on 0.3.4 on Win 7

**Comment by Stephen-Gates** [comment]
still present in 0.3.5 on Win 7
