### ISSUE TITLE
Find menu item order and shortcuts

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#780]
### Current Behaviour (for problems)
<img width="649" alt="screenshot 2018-05-10 21 34 53" src="https://user-images.githubusercontent.com/9379524/39867871-59539e54-549a-11e8-8971-0011adac5f3c.png">

### Expected Behaviour
> When reporting a problem, describe what should happen

- correct find previous shortcut
- fix replace next / previous order and shortcuts

<img width="207" alt="screenshot 2018-05-10 21 37 47" src="https://user-images.githubusercontent.com/9379524/39867895-7991b49e-549a-11e8-94ec-0e2f172bbdd5.png">

@mattRedBox I implemented this in https://github.com/ODIQueensland/data-curator/commit/0a1e908768af06abbabd063c5d810d47ce006a1d and fixed an error in https://github.com/ODIQueensland/data-curator/commit/f32b48f8bf3ab75ad36567d38e1304068e0646de but seem to have introduced a problem

Now find previous seems to invoke replace previous

Feel free to rollback and ignore my attempt at what I thought was a simple change - sorry

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version: 0.16.0 Develop branch
* Operating System and version:  macOS High Sierra 10.13.4

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates 
Yes I see the problem - easy fix - can fit this in

**Comment by mattRedBox** [comment]
Local testing:
While the application menu selection for 'Find previous' seems to work correctly, its current shortcut, Alt+Cmd+G, shows find feedback, but the value in the cell is replaced.
If cannot find issue, or a good substitute for the hot-keys combination, remove hot-keys from both:

- find previous

- replace previous
