### ISSUE TITLE
Application icon is broken in About pane

### ISSUE THREAD

**Issue by albreez** [ODIQueensland/data-curator#80]
### Desired Behaviour (for feature requests only)
Assuming the application icon is meant to display.

### Expected Behaviour (for problems)
as above

### Current Behaviour
Currently the icon displays as broken.

### Steps to Reproduce
Following the testing steps outlined here https://relishapp.com/odi-australia/data-curator/docs/data-curator/about
I,
1. Open Data Curator using the icon
2. Click on Data Curator from the Application menu
3. Select About Data Curator

### Your Environment
Windows 7
Data Curator version 0.2.3

Additional note - when following the Gherkin steps on Relish, the procedure is inconsistent with the application. For example;

Given I have opened Data Curator
When I select "About" from the menu > There is no About in the application menu. The menu item where this item is found is Data Curator (see image)
Therefore; the Gherkin script should read something like (please forgive my syntax);
Given I have opened Data Curator
When I select "Data Curator" from the application menu
And I select "About Data Curator" from the "Data Curator" menu 
Then... [script continues]

Please disregard this if the application is changing to comply with the original script.
![data curator error 02](https://user-images.githubusercontent.com/31878214/30408376-aa96fae6-9941-11e7-91c7-54f1ff03fcbe.JPG)

**Comment by Stephen-Gates** [comment]
Thanks @albreez 
This will be fixed in the next release

**Comment by Stephen-Gates** [comment]
Fixed for macOS in release 0.3.0

**Comment by Stephen-Gates** [comment]
Fixed for Windows in release 0.3.0
