### ISSUE TITLE
Data values don't appear when switching between toolbars 

### ISSUE THREAD

**Issue by louisjasek** [ODIQueensland/data-curator#803]
### Current Behaviour (for problems)
> When switching between toolbars (e.g. Guess, Column, Table, Provenance etc), when the Data Curator window is narrower than the actual dataset, then sometimes the data values do not appear. See picture below where this has happened.

![data not appearing](https://user-images.githubusercontent.com/36529635/40458262-7c4c2bd4-5f3e-11e8-8dd1-63fc288b5c68.PNG)

### Expected Behaviour
> Data values should always appear in the UI

### Steps to Reproduce

1. Open Data Curator using the icon
2. Open any CSV file
3. Reduce the size of the Data Curator window so you can't see all of the columns in your table
3. Switch between toolbars repeatedly. I find switching between Find (which appears on the left) and the others (which appear on the right) usually triggers it
4. Data values cannot be seen. To rectify you need to keep switching between toolbars, maximise the window or close data curator. It doesn't always fix itself without restarting data curator.

This only occurs in Windows. I tested in Mac and it seems fine.

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version: 0.17.0
* Operating System and version: Windows 10 Pro

**Comment by louisjasek** [comment]
@Stephen-Gates either I don't have permission to or I can't figure out how to add priority and a milestone. Could you please put this in the next milestone? What do you think for priority. My feel is it is high priority but at the bottom of the high priority list.

**Comment by Stephen-Gates** [comment]
@louisjasek if you [accept the invitation](https://github.com/ODIQueensland/data-curator/invitations) I previously sent, you should be able to assign labels and milestones

**Comment by louisjasek** [comment]
Thanks @Stephen-Gates just accepted it. Will do in future :)

**Comment by Stephen-Gates** [comment]
@louisjasek  you should also be able to go to the [milestone](https://github.com/ODIQueensland/data-curator/milestone/28) and reorder the issues by dragging them up or down. Let me know if you can't.

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates, @louisjasek 
Will do what I can here, but may be somewhat out of control (if it's in the hot render), particularly if only in 1 OS - perhaps just getting app to reselect table (although there will be a slight performance hit here) might be enough to get app/hot to re-render table.

**Comment by Stephen-Gates** [comment]
v0.18.1 I'm getting something similar now on macOS on opening a large data package (same data as used in #805)

<img width="310" alt="screenshot 2018-06-07 07 12 47" src="https://user-images.githubusercontent.com/9379524/41065564-5dd03c42-6a22-11e8-8965-c3f4612c7048.png">

**Comment by Stephen-Gates** [comment]
Have tested and I believe this is fixed 👍

**Comment by louisjasek** [comment]
agree :)
