### ISSUE TITLE
Unable to load valid (tbc) csv file

### ISSUE THREAD

**Issue by louisjasek** [ODIQueensland/data-curator#806]
### Current Behaviour (for problems)
> Data Curator throws error ('unable to parse data. there could be a problem with data format') when loading this CSV file: https://data.qld.gov.au/dataset/new-vehicle-registrations-by-year/resource/e6531fe2-a5aa-4a93-b954-465e679def78. CSV file appears valid when checking with CSVLint as well as manual check. @mattRedBox  could you check why this is throwing an error and fix it if something is wrong? 

### Expected Behaviour
> Should be able to open this file as normal

### Steps to Reproduce

1. Open Data Curator using the icon
2. Click File > Open > Comma Separated
3. Open the CSV file downloaded from: https://data.qld.gov.au/dataset/new-vehicle-registrations-by-year/resource/e6531fe2-a5aa-4a93-b954-465e679def78

### Your Environment

* Data Curator version: 0.17.0
* Operating System and version: Windows 10 Pro

AND

* Data Curator version: 0.17.0
* Operating System and version: Mac OS Sierra 10.12.6

**Comment by Stephen-Gates** [comment]
I got the same error in Data Curator v0.17.0, macOS High Sierra v10.13.4

The file is 7.7Mb, 65535 rows

When I tried validating using https://try.goodtables.io and uploading the file I got:

<img width="998" alt="screenshot 2018-05-27 12 41 12" src="https://user-images.githubusercontent.com/9379524/40582003-5dd89970-61ab-11e8-996e-48a37f8dcd19.png">

Providing the url instead, I got "valid table" but the validation reached a 1000 row limit:

<img width="998" alt="screenshot 2018-05-27 12 48 08" src="https://user-images.githubusercontent.com/9379524/40582031-49c45c3e-61ac-11e8-80e0-4706136747f7.png">

Using CSVLint with a URL I got an error:

<img width="1246" alt="screenshot 2018-05-27 12 54 14" src="https://user-images.githubusercontent.com/9379524/40582059-212cdf2a-61ad-11e8-8cc4-8bd661e24e7f.png">

We've had issues with UTF8 and data.qld.gov.au before.

Uploading the file to CSVLint, after ~30sec of validation I got:

<img width="1201" alt="screenshot 2018-05-27 12 58 13" src="https://user-images.githubusercontent.com/9379524/40582087-be3cf660-61ad-11e8-958d-9a379e773b56.png">

@mattRedBox  could this just be the timeout being set too low?

**Comment by mattRedBox** [comment]
Hi @louisjasek @Stephen-Gates 
When Data-curator opens that csv file, it baulks at this line:
`2017,Registration New Business,"TRAILERS ""R"" US",ATM OVER 1.02T,BOX TRAILER,1`
This is despite what you see in Excel import, which perhaps uses double quote as an escape?
The set of double double-quotes you see there is where Data Curator is having the issue.
While it might be the way to import/export into Excel, it doesn't fit frictionless csv standard.
Changing lines like that to:
`2017,Registration New Business,"TRAILERS 'R' US",ATM OVER 1.02T,BOX TRAILER,1`
(or something similar)
allows Data-Curator to parse the line correctly

**Comment by Stephen-Gates** [comment]
Thanks @mattRedBox

**Comment by Stephen-Gates** [comment]
Add a topic in https://ask.theodi.org.au/c/projects/data-curator
