### ISSUE TITLE
bareNumber radio button functions in reverse

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#807]
### Current Behaviour (for problems)

If bare number is selected (true) then 3kg should be valid, but 

<img width="574" alt="screenshot 2018-05-27 14 14 36" src="https://user-images.githubusercontent.com/9379524/40582400-961a7ae4-61b8-11e8-86dd-9023a7dbdba7.png">

and if bare number is not selected (false) then 3kg should be invalid, but 
<img width="550" alt="screenshot 2018-05-27 14 14 16" src="https://user-images.githubusercontent.com/9379524/40582403-aedcc94c-61b8-11e8-8cdd-758abb24fa1d.png">

### Expected Behaviour
behaviour is opposite

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version: 0.17.0
* Operating System and version: e.g. macOS High Sierra 10.13.4

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates
I think what we have is correct (but at any rate we simply send through to frictionless)

From [frictionless](https://frictionlessdata.io/specs/table-schema/#number):
`bareNumber...
If true the physical contents of this field must follow the formatting constraints already set out...
If false the contents of this field may contain leading and/or trailing non-numeric characters`

Am I reading this incorrectly - as the app behaviour you're describing seems correct to me?

**Comment by Stephen-Gates** [comment]
You’re correct! I read it wrong
