### ISSUE TITLE
Allow Data Curator to open a data file it is associated with by clicking on the file

### ISSUE THREAD

**Issue by gavinkennedy** [ODIQueensland/data-curator#808]
> Use the Issue Title above to provide a summary of the problem, feature request or other issue.
> Fill out the relevant sections below. Delete sections as appropriate.
> Provide as much detail as you can to help us help you.

### Desired Behaviour (for feature requests only)
In Windows you can associate a file type with an application so when you double click on that file type it would open in the application. For example, by default, if you double click an *.xlsx file it will open in Excel. I'd like CSV files to open in Data Curator by default, so when I double click a file it will be opened by Data Curator.

I understand this equates to allowing command line arguments telling DC what to open when it starts up.

### Your Environment
> Windows 10
* Data Curator version: 0.17
* Operating System and version: n/a

**Comment by Stephen-Gates** [comment]
Hi @gavinkennedy 
I think we already have this issue in the backlog https://github.com/ODIQueensland/data-curator/issues/285

If you agree we've got it covered, please close this issue.

**Comment by gavinkennedy** [comment]
Yes, same same, but I understand it is parameterisation of the executable. I discussed with Matt and he may not have realised that is what 285 was about. I will discuss with him tomorrow and update your ticket accordingly.

Gav

Sent from my iPhone

On 29 May 2018, at 2:45 pm, Stephen Gates <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @gavinkennedy<https://github.com/gavinkennedy>
I think we already have this issue in the backlog #285<https://github.com/ODIQueensland/data-curator/issues/285>

If you agree we've got it covered, please close this issue.

**Comment by Stephen-Gates** [comment]
Closing in favour of #285
