### ISSUE TITLE
Find and Replace

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#81]
I'm thinking about a find and replace feature and I'd like your input.

## Suggested behaviour

On selecting Find in the menu or using a shortcut, display a panel at the bottom of the screen:

![find-and-replace](https://user-images.githubusercontent.com/9379524/30408122-126b19ce-9940-11e7-8ed2-aee8dc9fc4f5.png)

Users can press the buttons, or in some cases a keyboard shortcut, to:

- find the value within the current column or across the table
- find the next or previous value 
- replace the value with another
- replace all the values with another

## Other Ideas

- Implement the solution in the Toolbar
<img width="655" alt="screenshot 2017-09-14 11 40 51" src="https://user-images.githubusercontent.com/9379524/30408375-a839d5ac-9941-11e7-8b46-3e550fc82e50.png">

What do you think @albreez @abhiravbansal @TacoSandwich

**Comment by Stephen-Gates** [comment]
/remind me to write the acceptance test in 1 week

**Comment by Stephen-Gates** [comment]
@louisjasek thoughts on the UI? I'm leaning towards toolbar implementation as this feature will be used with error messages that may be displayed in the bottom panel.

@mattRedBox thoughts on implementation?

**Comment by Stephen-Gates** [comment]
Excel's UI

<img width="437" alt="screenshot 2018-03-18 22 14 46" src="https://user-images.githubusercontent.com/9379524/37565718-da4bb598-2af9-11e8-9e6b-f7937851cb76.png">

<img width="451" alt="screenshot 2018-03-18 22 13 27" src="https://user-images.githubusercontent.com/9379524/37565715-d9ba4e0a-2af9-11e8-9716-5651d7a503ce.png">

<img width="451" alt="screenshot 2018-03-18 22 14 12" src="https://user-images.githubusercontent.com/9379524/37565717-da034fba-2af9-11e8-86d8-bc0f65ac6b14.png">

**Comment by Stephen-Gates** [comment]
Numbers UI

<img width="534" alt="screenshot 2018-03-18 22 18 20" src="https://user-images.githubusercontent.com/9379524/37565741-53f06f24-2afa-11e8-8cad-86175736af55.png">

<img width="524" alt="screenshot 2018-03-18 22 17 54" src="https://user-images.githubusercontent.com/9379524/37565740-53a6f7fe-2afa-11e8-9503-c42a4d372380.png">

**Comment by Stephen-Gates** [comment]
Atom UI

<img width="678" alt="screenshot 2018-03-19 06 41 37" src="https://user-images.githubusercontent.com/9379524/37570841-b5aefaaa-2b40-11e8-8e4b-5bf257269edc.png">

R

<img width="635" alt="screenshot 2018-03-19 06 57 30" src="https://user-images.githubusercontent.com/9379524/37571056-82c60b08-2b43-11e8-8a2a-0d46b84761c3.png">

Xcode

<img width="800" alt="screenshot 2018-03-19 07 00 12" src="https://user-images.githubusercontent.com/9379524/37571058-8377a1a6-2b43-11e8-99ff-cfef47fefa8e.png">

<img width="795" alt="screenshot 2018-03-19 06 59 57" src="https://user-images.githubusercontent.com/9379524/37571057-8313b02e-2b43-11e8-95b6-c647baf708ef.png">

**Comment by louisjasek** [comment]
@Stephen-Gates I'm not too fussy. If you think toolbar implementation would be better given the rest of the UI then let's go with that.

**Comment by Stephen-Gates** [comment]
Draft acceptance tests 

- https://relishapp.com/odi-australia/data-curator/docs/edit/find 
- https://relishapp.com/odi-australia/data-curator/docs/edit/replace-in-column
- https://relishapp.com/odi-australia/data-curator/docs/edit/replace-in-table

**Comment by Stephen-Gates** [comment]
Command | Shortcut
-|-
Find | Cmd + F
Find Next | Cmd +G 
Find Previous | Shift + Cmd + G
Replace Next | ?

**Comment by Stephen-Gates** [comment]
May be easier and quicker to implement in side panel. Stephen to mockup

**Comment by louisjasek** [comment]
I'm fine with this @Stephen-Gates

**Comment by louisjasek** [comment]
If there is an easier way to implement though, go for it

**Comment by Stephen-Gates** [comment]
<img width="631" alt="screenshot 2018-03-21 23 17 49" src="https://user-images.githubusercontent.com/9379524/37711932-21843398-2d5e-11e8-8336-1a50cda977d8.png">

**Comment by Stephen-Gates** [comment]
We’re going with the side panel design

**Comment by Stephen-Gates** [comment]
Tests:
- [Find](https://app.cucumber.pro/projects/data-curator/documents/branch/develop/test/features/find/find.feature)
- [Replace](https://app.cucumber.pro/projects/data-curator/documents/branch/develop/test/features/find/replace.feature)

**Comment by Stephen-Gates** [comment]
Replaced by #633 and #634
