### ISSUE TITLE
When opening new data tabs they all have the same default name

### ISSUE THREAD

**Issue by albreez** [ODIQueensland/data-curator#82]
### Desired Behaviour (for feature requests only)
Suggestion only - Give each new tab a unique name e.g. Untitled.csv then Untitled2.csv then Untitled3.csv by default
This is to avoid errors and possible confusion later on.

### Current Behaviour
Each time a new tab is opened it is given the same name "Untitled.csv" by default. 

### Steps to Reproduce
Applies to all 3 methods of opening a new data tab
1. Select File > Select new
or 2. Press Ctrl + N
or 3. Click on the + next to the open tabs

### Your Environment
Data Curator version 0.2.3
Windows 7

**Comment by Stephen-Gates** [comment]
Thanks for the suggestion @albreez 
I think it's a good idea. I've already dropped the file extension from the tab name https://github.com/ODIQueensland/data-curator/commit/8f21ef044aa637cdc97b12df98ba79d9688af9a6 

I'll add the idea to the feature for future implementation

**Comment by Stephen-Gates** [comment]
Fixed in release 0.3.0 for macOS

**Comment by Stephen-Gates** [comment]
Fixed for Windows in release 0.3.0
