### ISSUE TITLE
Can't open datapackage from a localhost URL

### ISSUE THREAD

**Issue by chrislove** [ODIQueensland/data-curator#834]
### Current Behaviour
Unable to open data packages from localhost URLs
When you attempt to open a datapackage from a http://localhost/.... URL an error is displayed and the and the package isn't loaded when you click Open URL

### Expected Behaviour
No error message and open the data package from the specified localhost URL.

### Steps to Reproduce
1. Run Data Curator
2. Choose File -> Open Data Package -> json from URL
3. Enter  http://localhost/anything

The message "The url-dialog field is not a valid URL." is displayed within the dialog.

### Your Environment
Windows 10 Enterprise
Data Curator version 0.18.5

**Comment by mattRedBox** [comment]
Hi @chrislove 
You're correct - the validation on the URL is looking for a typical external URL format, with the required dot-3 letter designation.
In an ideal wishlist: the menuitems would have had an extra one reading:
- zip from URL...
- zip from file...
- json from URL...
- **json from file...**

Unfortunately in the prioritising of functionality, open json from file was [cut](#729).
I've linked this ticket in to the existing reference, should this be prioritised again to add as a new feature.
