### ISSUE TITLE
Data Curator version 2 - what features would you like?

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#84]
In Data Curator version 1, we'll deliver a set of [core features](https://github.com/ODIQueensland/data-curator#planned-features).

I'm starting to think about version 2. **I'd love to hear your ideas**. 

Here's mine...

# 1. Tools to help package and publish data

## 1.1 Set Preferences

[Set preferences](https://relishapp.com/odi-australia/data-curator/docs/backlog/set-preferences) for default values and behaviours to speed up packaging of data.

## 1.2 Publish data package to CKAN

Using securely stored API credentials enable [publishing the data package to CKAN](https://relishapp.com/odi-australia/data-curator/docs/version-2/publish-data-package) 

## 1.3 Import Column Properties

Access a library of pre-defined column properties and [import column properties](https://relishapp.com/odi-australia/data-curator/docs/version-2/import-column-properties) to apply consistent descriptions and constraints to similar data

## 1.4 Print

[Print](https://relishapp.com/odi-australia/data-curator/docs/backlog/print) sample data and metadata to show to Data Custodian as part of the open data release approval process

## 1.5 Open data from other sources

Open files directly from the web instead of downloading them to your computer.

* Open from csv file stored on web
* [Open from Google sheet](https://relishapp.com/odi-australia/data-curator/docs/backlog/open-a-google-sheet)
* [Open a file using Drag and drop](https://relishapp.com/odi-australia/data-curator/docs/backlog/open-file-with-drag-and-drop)

## 1.6 Support Custom CSV Dialects

Sometimes publishers need to [open](https://relishapp.com/odi-australia/data-curator/docs/backlog/open-an-custom-csv-dialect-file) and save CSV files using Custom CSV Dialects 

# 2. Tools to help correct data

## 2.1 Create constraint from column

To create an [enumeration constraint](https://relishapp.com/odi-australia/data-curator/docs/version-2/create-constraint-from-column) based on the data in the column:

* read the data in a column 
* determine the set of unique values
* automatically generate an enum constraint in the column properties

## 2.2 Create look-up table from column

Use the set of unique column values to [create a look-up table and a foreign key relationship](https://relishapp.com/odi-australia/data-curator/docs/version-2/create-lookup-table-from-column) between tables.

## 2.3 Validate foreign keys against data at a url

[Validate data](https://relishapp.com/odi-australia/data-curator/docs/tools/validate-table
) against a shared code-list stored at a url. This allows organisations to use a shared code-list to lookup valid values.

This is dependent on an anticipated change to the Frictionless Data specification

## 2.4 Find, Replace, Sort and Filter

* [Find](https://relishapp.com/odi-australia/data-curator/docs/backlog/find) and Replace within a Table
* Find and Replace within a Column
* Sort Columns
* Filter Column

## 2.5 Validate as you type

[Validate data](https://relishapp.com/odi-australia/data-curator/docs/backlog/validate-as-you-type) as you type data in a cell, check it matches the Type, Format and Constraints

# 3. Tools to data consumer understand and view the data

## 3.1 Generate data quality information and report

Read the data to [generate data quality statistics](https://relishapp.com/odi-australia/data-curator/docs/backlog/data-quality-information). Include the [report](https://relishapp.com/odi-australia/data-curator/docs/backlog/sample-data-quality-information) in the data package. 

## 3.2 Define a default visualisation

Use an [emerging specification](http://specs.frictionlessdata.io/views/) to [set a default view](https://relishapp.com/odi-australia/data-curator/docs/backlog/set-view-properties) for a [data package](https://datahub.io/core/gold-prices)

## 3.3 Read-only mode

Prevent unintended changes being made to the data and metadata

# 4. Improve application reach and support

## 4.1 Check for Updates

Automatically [check for application updates](https://relishapp.com/odi-australia/data-curator/docs/version-2/check-for-update)

## 4.2 Configuration file

The collection of column, table and data package properties will be driven by a configuration file. This file will enable:

* new properties to easily added to the application as standards change
* [setting default values](https://relishapp.com/odi-australia/data-curator/docs/version-2/set-preferences-using-configuration-file) across an organisation enabling consistent publishing 
* supporting other metadata standards e.g. W3C CSV for the Web

## 4.3 Improve Help, Support and Onboarding

* provide link to external help website and update content to match application features
* embed help in app so internet access is not needed
* provide onboarding tour of key features when user opens the app for the first time

## 4.4 Publish to App Store and provide ongoing support

* Provide confidence and ease to install application 
* Fix bugs quickly

**Comment by albreez** [comment]
I'm pasting my comments from Comma Chameleon as I think they are still relevant here. 

It would be good if the tools used by data publishers could be combined into the one application. Comma Chameleon would be the most logical place as it would enable people like myself to;

1. import an Excel spreadsheet containing raw data, (DC does this) 
2. convert the data to CSV using a standard dialect, (DC does this)
3. check the data for quality issues (which could be highlighted so the user can see them and decide to correct them or not)
4. correct those errors, 
5. build a JSON schema which complies to the expected open data standard, 
6. validate the data against the schema and,
7. create the data package
8. test publish it to Octopub and even get feedback using Github
9. All in the one place.

I love all the tools but a one stop shop would be a publisher’s dream.

Please feel free to provide this feedback to the developers. I’m loving their work so far.

**Comment by Stephen-Gates** [comment]
Hi @albreez - thanks for your suggestions. 

3. should be done via [Generate Data Quality Information](https://relishapp.com/odi-australia/data-curator/docs/version-2/data-quality-information) that would product a [report](https://relishapp.com/odi-australia/data-curator/docs/version-2/sample-data-quality-information)

4. I'm not sure how these quality issues could be corrected - do you have an example?

5. Are you suggesting:
  
   - An `Import a Schema` function and then let user enter data and validate against that schema? This would be an extension of [Import Column Properties](https://relishapp.com/odi-australia/data-curator/docs/version-2/import-column-properties)
   - or do you mean, use set column/table/data package properties to define an Open Standard that does not have a JSON representation?

  [6.](https://relishapp.com/odi-australia/data-curator/docs/tools/validate-table) & [7.](https://relishapp.com/odi-australia/data-curator/docs/tools/export-data-package) will be in release 1.0

8. Octopub does not support this yet  https://github.com/theodi/octopub/issues/477 

9. I don't think we'll attempt to combine Data Curator and other desktop tools like Open Refine. Some of the schema definition and validation tools are being integrated into CKAN however that presumes you're happy to send your data to the web for validation. Data Curator's differentiator is that all work happens locally on your computer before publishing to the web.

Some column resizing is automatic but a little buggy on insert column. We'll look at the [HandsonTable](https://handsontable.com/examples.html?headers) features to see what can be added easily. Feel free to add a feature request for this.

**Comment by Stephen-Gates** [comment]
@albreez just adding features that will behave like [this example](https://handsontable.com/examples.html?manual-resize&manual-move&headers&sorting) except for move columns
