### ISSUE TITLE
Save does not work (blocked)

### ISSUE THREAD

**Issue by jenstornell** [ODIQueensland/data-curator#840]
I can drag in a CSV file and it loads correctly, which even most other spreadsheet programs can't get right.

I edit it a bit but then when I press CTRL + S (save) it does not save. It's blocked. Instead I need to do a "Save as" and browse to find the file I'm currently editing.

The reason for it is that it's not aware if my CSV file is comma separated or not. So it could load it and figure it out but can't save it. It should probably somehow remember what format I loaded it in and save it in the same format.

I'm on Windows 10.

**Comment by mattRedBox** [comment]
Thanks for raising this @jenstornell. I'll look into this.

**Comment by mattRedBox** [comment]
Hi @jenstornell 
Pending next release, fix for drag/drop csv file is in. Note that if you require the save to remember the format, you'll need to use File->Open menu to tell Data-Curator the type. Drag/drop only supports csv file by default (but you can then do Save-As to change type).

**Comment by jenstornell** [comment]
@mattRedBox I'm not sure I understand it correctly and fully. Will "Save" now work as in "CTRL + S"?

**Comment by mattRedBox** [comment]
Hi @jenstornell 
It should in the next release - which must go through the usual channels on this side. At the moment, the fix is only in the development build.
