### ISSUE TITLE
Tab create a new column, but how to get back?

### ISSUE THREAD

**Issue by jenstornell** [ODIQueensland/data-curator#841]
Ooops! When pressing tab one time too much I end up with a new column. That's probably expected. But I want to undo that move so I tried with SHIFT+ TAB to take it back but it does not work. Instead it goes back, which also probably is expected.

I'm not sure if it's an issue or a question, but how can I remove that column I'm on with just the keyboard?

Windows 10.

**Comment by Stephen-Gates** [comment]
@jenstornell there isn't a keyboard shortcut to delete a column - we felt that was a little dangerous.

You can find all the keyboard shortcuts in the Help menu.

**Comment by jenstornell** [comment]
If the whole column is empty, delete it on shift + tab?

**Comment by mattRedBox** [comment]
Hi @jenstornell 
The OS' regular 'Undo' function (Cmd/Ctrl Z) should work to undo something like a new column - however it may not function quite as you expect as, for example, if you started with 3 columns and if you quickly created 2 more columns, it may undo all of that and go back to 3 columns again. This is often dependent on OS-behaviour.
And yes, at first it may seem odd that while TAB can create a new column, if you move to the end, as a convenience, it creates another column, but as TAB is also used to move across existing columns, shift-TAB will move back across existing columns.
Of course, to ensure that you get the behaviour you require, right-click on the cell, and choose 'Remove Column(s)' and that will remove the current column for you.
