### ISSUE TITLE
Cannot open a file from the command line

### ISSUE THREAD

**Issue by sizezero** [ODIQueensland/data-curator#848]
Comma Chameleon could take a CSV file as a command line argument. This
made it a really nice tool for quick edits.

Datacurator does not seem to do anything with command line
arguments. I need to run the program, wait for it to open and then run
the command file open > comma separated, in order to open a CSV
file. Is this intentional? Could this be related to my linux build or
the way I run the program?

This issue was tested from an early October 2018 linux build.
commit e479405049bf47a9564d0a6259c6403f32e8edc0

**Comment by mattRedBox** [comment]
Hi @sizezero
Yes, during the project adoption, unfortunately this behaviour was given low priority so we didn't implement in Data Curator. I will certainly ask where this can be considered again, but it may not be adopted in the immediate future.

**Comment by Stephen-Gates** [comment]
Related issue that may be more widely used is #63 Drag'n'Drop file to open
