### ISSUE TITLE
Silently converts newlines to native format

### ISSUE THREAD

**Issue by sizezero** [ODIQueensland/data-curator#849]
When I load a CSV file in linux and write it out it converts line
endings to LF (unix) no matter what the line endings of the source
file were. I'm not sure what the behavior is for the Windows and Mac
clients but I suspect it's similar. It would be nice if the tool
honored the line endings of the input file and wrote out the same line
endings.

This issue was tested from an early October 2018 linux build.
commit e479405049bf47a9564d0a6259c6403f32e8edc0

**Comment by mattRedBox** [comment]
Hi @sizezero 
For Data Curator, there is an attempt to balance between OS considerations (but again there is no support built in for Linux atm, only Windows and Mac), as well as best effort to align with the [frictionless specification](https://frictionlessdata.io/specs). For CSV dialect, line terminators by default are: '\r\n', which we adopt in Data Curator. With more support, we could add these in as part of Preferences/Settings to allow the user to change these but this feature unfortunately didn't make the cut in project work up til now.
At the moment, AFAIK, yes you are correct, the file is saved, honouring the line terminators/endings of the source. I guess here we were trying to make sure that Data Curator wasn't making any implicit changes to the resources without the user being aware. Whether or not this should be the behaviour I'm not entirely sure. I guess, like other tools, what would be ideal would be a Settings/Preference where the user could choose whether to use OS-default when saving or to honour the source. 
However, with export, the default dialect from the frictionless libraries we use, the default line terminators, which is \r\n will be used, as outlined in the [frictionless spec](https://frictionlessdata.io/specs/csv-dialect/)

**Comment by sizezero** [comment]
> At the moment, AFAIK, yes you are correct, the file is saved, honouring the line terminators/endings of the source. I guess here we were trying to make sure that Data Curator wasn't making any implicit changes to the resources without the user being aware.

The above behavior that you describe is not what I am seeing. Are you saying that the windows and mac versions of data curator preserves the line endings of the source CSV file but the linux version does not?

On linux:
- create a CSV file with windows carriage returns (CRLF)
- open file with linux data curator
- make a trivial change and save
- all line endings in the written CSV file are converted to unix (LF)

I would expect all versions of data curator to preserve the source line endings of any CSV file.

**Comment by mattRedBox** [comment]
Hi,
Sorry some of what I've said above isn't correct. However think this one is OK. The frictionless standard for csv dialect means that by default line terminators will be written out as `\r\n`. I've tested in linux build and whatever the incoming line terminators, files are consistently being written out as `\r\n`.
