### ISSUE TITLE
Prevent deletion of all rows and columns

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#85]
### Expected Behaviour (for problems)
When I delete all rows and columns, leave a 1x1 table in place

### Current Behaviour
You can delete all rows and columns leaving you with 

<img width="190" alt="screenshot 2017-09-14 19 45 08" src="https://user-images.githubusercontent.com/9379524/30423209-839a064c-9985-11e7-90d3-1e7f1a01dbc8.png">

### Steps to Reproduce

1. Open Data Curator using the icon
2. Place the cursor in Row 1
3. Right click, delete row

### Your Environment

* Data Curator version 0.2.3
* Operating System macOS Sierra 10.12.2

**Comment by Stephen-Gates** [comment]
Also occurs on Windows 7

**Comment by mattRedBox** [comment]
Fixed in support release.
