### ISSUE TITLE
On exit, does not prompt to save unsaved edits

### ISSUE THREAD

**Issue by sizezero** [ODIQueensland/data-curator#851]
- run datacurator
- open a CSV file
- edit a cell, hit enter to submit cell changes
- exit datacurator
- edits are silently discarded; most/all editors prompt the user to save unsaved edits

**Comment by mattRedBox** [comment]
Hi @sizezero 
Might be different behaviour you're seeing on Linux (or confirm that you're using the release, not the dev build), but using the release artifact, you should see:

<img width="460" alt="screen shot 2018-10-12 at 9 47 49 am" src="https://user-images.githubusercontent.com/5482657/46839979-07bfc700-ce04-11e8-90ac-6cc7135306bf.png">

**Comment by sizezero** [comment]
I'm not sure if I performed a release or a dev build. I thought there were no linux releases available for download. Here's what I did:

- `git clone https://github.com/ODIQueensland/data-curator.git`
- `yarn run dev`
- `yarn run build`
  - this above command failed but maybe it did a partial build?
- `.electron-vue/build.js && yarn run electron-builder --linux AppImage`
- was able to run `build/linux-unpacked/datacurator` from the command line

Is there a different way to build that makes a "release build"?

**Comment by mattRedBox** [comment]
Hi @sizezero 
I've started looking at improving our release/ci process - I might be able to put in more support for linux here as I can also see others keen for this integration: #830 #247 . Just to draw a line for now, I'll start with AppImage and test on Ubuntu 16x LTS. From here I can look at what happens with the linux build artifact.

**Comment by sizezero** [comment]
Thanks!

Let me know if I need to build the production image (and how) or if it will a be available for download.

**Comment by Stephen-Gates** [comment]
See also #68 for an issue about potentially losing unsaved work

**Comment by mattRedBox** [comment]
Hi

Unless I've misunderstood the issue, closing this one off as my linux build shows closing message ok.
![image](https://user-images.githubusercontent.com/5482657/60702730-124a5f80-9f43-11e9-9662-63f4ed281482.png)
CI includes all tests for linux and while it isn't available for download from releases, can be built simply enough (for AppImage), by running `yarn build`
