### ISSUE TITLE
Issues with scrolling and large tables (>500 rows)

### ISSUE THREAD

**Issue by albreez** [ODIQueensland/data-curator#86]
This issue was discovered when I tried testing DC using a table containing 1000 rows to see how it would handle. There are a two issues here;
1. The scrollbar behaviour is not as expected, especially the horizontal scrollbar
2. Scrolling of the table vs scrolling of the application and the visibility of the menus et. al.

### Desired Behaviour
If the number of columns in the table exceed the number of columns that can be displayed on the screen the horizontal scrollbar should display at the bottom of the screen, irrespective of the number of rows loaded. 
When user clicks on the horizontal scrollbar at the bottom of the screen it should allow them to move it  sideways to scroll through the columns offscreen. 
When user clicks on the vertical scrollbar at the right of the screen it should allow them to move it up and down to scroll through rows offscreen. 
Additional rows should load as the user scrolls down until the last row at the bottom of the table is reached.
The top menu (Validate | Column | Table etc.), tabs, column reference (A,B,C,D etc.) and column headings should all remain visible as the user scrolls down.
To save data and load time, DC should only display a set number of rows by default (which it appears to do). However, there needs to be an option that allows the user to increase the maximum number of rows to load, including loading all rows.
There also needs to be the ability to pin and unpin the top menu and tabs to the top of the screen so that the user has the ability to control whether they remain visible or be hidden as they scroll. 

### Current Behaviour
When a large table is loaded that contains more than the maximum number of rows visible on the screen DC only loads the rows that can be displayed. This is fine, but when the user scrolls down and clicks on the horizontal scrollbar to scroll sideways, DC loads additional rows at which point the horizontal scrollbar (which is supposed to allow the display of additional columns, not rows) disappears.
This means the user cannot use the horizontal scrollbar to navigate sideways until all rows in the table are loaded. If there are >100 rows in the table, this will become a problem.
The top menu (Validate | Column | Table etc.), tabs, column reference (A,B,C,D etc.) and column headings  also disappear from view if the scrollbars are used. 
There is no easy way to navigate to the last row at the very bottom of the table.

### Steps to Reproduce

1. Open Data Curator using the icon
2. Open a new file (any type) with >100 rows
3. Start scrolling

### Your Environment
Data Curator version 0.2.3
Windows 7

### Images
![data curator issue- large tables 1](https://user-images.githubusercontent.com/31878214/30526605-c57b615e-9c60-11e7-9abe-efca2767177f.jpg)
![data curator issue- large tables 2](https://user-images.githubusercontent.com/31878214/30526610-d40b23d0-9c60-11e7-88b1-8a3c94e61bbd.jpg)

**Comment by Stephen-Gates** [comment]
related to #42

**Comment by Stephen-Gates** [comment]
Working well on macOS with Data Curator v0.3.1

Will test on windows when 0.3.1 binary is released

**Comment by Stephen-Gates** [comment]
Tested works well on Windows 7.
