### ISSUE TITLE
Rows do not align with the row reference grid

### ISSUE THREAD

**Issue by albreez** [ODIQueensland/data-curator#87]
### Expected Behaviour (for problems)
Data rows in the table should align with the row reference grid

### Current Behaviour
See image - the rows do not align with the grid (the blue line showing the selected row isn't straight)

### Steps to Reproduce
1. Open Data Curator using the icon
2. Open a data file (e.g. .csv)
3. Select a row and see if it is properly aligned with the grid.

### Your Environment
Data Curator version 0.2.3
Windows 7
![data curator issue- misaligned rows](https://user-images.githubusercontent.com/31878214/30526954-46cfde9c-9c66-11e7-9cff-60978fc18128.jpg)

**Comment by Stephen-Gates** [comment]
I get similar behaviour when using a [very large csv](https://certificates.theodi.org/en/datasets) on macOS 

![row-alignment](https://user-images.githubusercontent.com/9379524/30681049-a028e5a6-9ee6-11e7-8374-cbb92fc6174f.PNG)

**Comment by Stephen-Gates** [comment]
Re-tested and fixed in 0.3.2
