### ISSUE TITLE
Cut, copy and paste menu items not functioning

### ISSUE THREAD

**Issue by albreez** [ODIQueensland/data-curator#88]
### Expected Behaviour (for problems)
Cut: https://relishapp.com/odi-australia/data-curator/docs/edit/cut
Copy: https://relishapp.com/odi-australia/data-curator/docs/edit/copy
Paste: https://relishapp.com/odi-australia/data-curator/docs/edit/paste

### Current Behaviour
Functions do not work when using the menu commands.
Keyboard shortcut commands work.

### Environment
* Data Curator version 0.2.3
* Windows 7

**Comment by Stephen-Gates** [comment]
@albreez adding Cut and Copy to the Context menu seems to be native Handsontable functionality 

- demo https://handsontable.com/examples.html?context-menu
- doco https://docs.handsontable.com/0.34.4/demo-context-menu.html 


Shouldn't be too hard to add.

**Comment by Stephen-Gates** [comment]
I have temporarily disabled the menu item in https://github.com/ODIQueensland/data-curator/commit/f6eb0fb8d8ba8eb3821cadf3f76f7bc3defcb6e4 so it's not a problem in the Beta. Will fix in future release.

**Comment by Stephen-Gates** [comment]
menu items enabled in 0.3.1 to allow keyboard shortcuts to work but menu items don't work yet
