### ISSUE TITLE
Remove support forum link in menu and about box

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#887]
Remove support forum link in menu as it the forum is no longer available due to the ODI Australia Network wrapping up.

The note in the About panel, `Beta version 1.0.0 - Access the support forum or report issues via the Help menu` should be removed.

**Comment by mattRedBox** [comment]
Ok np - once sponsors have oked more work, this will be an easy one to do with no time spent. Thanks @Stephen-Gates

**Comment by Stephen-Gates** [comment]
As a suggestion we could change the menu item `Support Forum` to `Data Curator Help` and link to https://frictionlessdata.io/articles/datacurator/

**Comment by Stephen-Gates** [comment]
I forgot I started building a [help site](https://odiqueensland.github.io/data-curator-help/index.html). It is no where near complete but just adding a note here in case me, or someone else, decides to build it out.

**Comment by Stephen-Gates** [comment]
@mattRedBox can you please change the menu item `Support Forum` to `Data Curator Help` and link to https://odiqueensland.github.io/data-curator-help/ 

I've been working on the Help site this weekend and I think I can finish it off over the coming weeks.

**Comment by markwheels** [comment]
Hi @mattRedBox and thanks @Stephen-Gates for this excellent work. Agreed with this wording and link suggestion.

**Comment by mattRedBox** [comment]
Resolved.

**Comment by Stephen-Gates** [comment]
Confirmed working in 1.1 beta
