### ISSUE TITLE
Can't set column name

### ISSUE THREAD

**Issue by kayakr** [ODIQueensland/data-curator#901]
### Current Behaviour (for problems)
> When reporting a problem, describe what happens that isn't expected behaviour?

When working with Column tool, can't set column name; Name widget in right sidebar is disabled. This is for content added directly into Data Curator, not loaded from an existing file.
Later during validation, the error "Every Column property, including the column properties of any foreign keys, must have a unique 'name'." shows.

See attached screenshot.
<img width="1516" alt="Screen Shot 2019-04-03 at 2 41 52 PM" src="https://user-images.githubusercontent.com/208184/55447167-28ccdc00-561f-11e9-833d-367bbefcaa12.png">

### Expected Behaviour
> When reporting a problem, describe what should happen

I can specify the column name, then validate the file.

### Steps to Reproduce
> When reporting a problem, provide a set of steps so others can reproduce the problem.

1. Open Data Curator using the icon
2. Enter several columns and rows
3. Try and set the column data incl. name and title. Title is ok, but name can't be specified.

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version: 1.0.0
* Operating System and version: e.g. macOS High Sierra 10.13.6

**Comment by mattRedBox** [comment]
Hi @kayakr 
It looks like we need to address our help text here as it's not intuitive enough.
The  reason why 'name' is disabled as this is meant to come directly from the header row. I think the idea here was that it forces users to ensure that the Column->name attribute always matches the header row.
So to see the Column name, if you click on:
Tools menu->Header Row
This should:
- select the Header row as enabled
- Populate each of the Column->Name(s)
If I've understood this correctly (please let me know if not), I'll add this to the candidates for our sponsors to consider for upcoming enhancements/bug fixes. Obviously this behaviour is not obvious, so maybe we could improve the tooltip text here to show how name is populated.

**Comment by kayakr** [comment]
@mattRedBox Thanks for the prompt response. I hadn't noticed the Header Row menu item. After seeing your reply I loaded the CSV and it detected the header row and the column names were preset.

So things are working ok, thanks, but some UI improvements would be welcome. E.g. if column name is empty, suggest they set a header row (if one isn't set).

**Comment by mattRedBox** [comment]
Ok good idea, will put suggestion forward.
Thanks @kayakr

**Comment by mattRedBox** [comment]
Hi @markwheels @kayakr 
I think maybe the way to make this more helpful (without introducing too much awkwardness), is to 

- improve the text in help text on the column properties menu (so suggest user set column properties if there is no name present)
- we could add something extra to Validation message here too (maybe just a permanent hint to set header row)?
Otherwise can just change the text here (rather than any checking whether the name is set or of something else?)

**Comment by Stephen-Gates** [comment]
@mattRedBox So you're suggesting fixing the text that appears when you hover over the Name label in the Column Properties panel?

<img width="792" alt="Screenshot 2019-05-31 20 07 10" src="https://user-images.githubusercontent.com/9379524/58699061-f43b8d80-83df-11e9-835f-8345294a65a1.png">

**Comment by markwheels** [comment]
Hi @mattRedBox @Stephen-Gates, following Matt's suggestion, I can propose wording to be added after the existing help text and validation error message: 'Where no name is set, select 'Header Row' from the Tools menu to assign column names.' Thoughts?

**Comment by mattRedBox** [comment]
Sounds OK to me @markwheels
