### ISSUE TITLE
Open Data Package Error

### ISSUE THREAD

**Issue by kayakr** [ODIQueensland/data-curator#903]
### Current Behaviour (for problems)
> When reporting a problem, describe what happens that isn't expected behaviour?

On startup, Data Curator opens with a tab Untitled0 with 1 row with three empty cells. If I try to open a previously saved data package using File > Open Data Package > zip from file... I get a file dialog, I chose a previously saved data package, Data Curator shows "Open Data Package Error" and "with an opened tab".

### Expected Behaviour
> When reporting a problem, describe what should happen

I can load a previously saved data package with data values and json data populated.

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version: 1.0.0
* Operating System and version: macOS High Sierra 10.13.6

**Comment by mattRedBox** [comment]
Hi @kayakr 
Thanks for raising this. I'll add it to the short-list for our sponsors to consider.

**Comment by mattRedBox** [comment]
Hi @kayakr 
Not sure what the specific error is that you're getting but when I downloaded the latest .dmg again, and try I don't get open data-package error (perhaps I had an older version before) - not sure why, but it might be worth trying just to rule this out.
Is there a specific error that is shown - (please try downloading latest again).
For the newly opened tab, this is the usual behaviour so as to ensure Data-Curator doesn't overwrite/lose needed previous/existing data.
If the data-package does not contain sensitive data, please attach - that way can perhaps replicate more easily if our sponsors approve this request.

**Comment by mattRedBox** [comment]
Closing as won't fix. Please re-open if after latest download, issue occurs again.
