### ISSUE TITLE
Filenames must be unique test is not case sensitive 

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#92]
In https://github.com/ODIQueensland/data-curator/commit/9ab265c6e9b688cbb0750dc4557510cd71a52b54 there is now a check for unique filenames in the data package. This test is not case-sensitive.

<img width="538" alt="screenshot 2017-09-21 08 14 58" src="https://user-images.githubusercontent.com/9379524/30670568-2783ae3c-9ea6-11e7-984e-5999cc7e1d30.png">

### Expected Behaviour (for problems)

Uniqueness check is case-sensitive

### Steps to Reproduce

1. Open Data Curator using the icon
2. add data in tab and save as file1.csv
3. add data in a new tab and save as FILE1.csv
4. not prevented from saving file

### Your Environment

* Data Curator version 0.3.0 + above commit  - local build
* Operating System  macOS Sierra 10.12.2

**Comment by Stephen-Gates** [comment]
Works in Windows 7, Data Curator 0.3.5

**Comment by Stephen-Gates** [comment]
Consider forcing filenames to be lowercase given the [specification](https://frictionlessdata.io/specs/data-resource/#name)

**Comment by mattRedBox** [comment]
Filenames different to table name (in spec) - leaving as case sensitive. Fixed code bug.
