### ISSUE TITLE
Add case-sensitive toggle for Find/Replace

### ISSUE THREAD

**Issue by mattRedBox** [ODIQueensland/data-curator#924]
Following work on #705, keeping Find and Replace consistent, it may be beneficial to allow the user to toggle this behaviour.
When this work begins, both find and replace will be case insensitive. One of the reasons for this is that there is support for 'diacritics' built in (important for other language use), which use library that hardcodes various glyphs/characters to our regular English alphabet. Trying to split this out into what should/would be lowercase or uppercase is subjective (e.g., pick which one of these you would deem as uppercase 'I' or lowercase 'i' or something else entirely: ḭƗɨɨ̆ᵻᶖİiIıɪ  )
While I don't think case sensitivity will solve the problem just listed, a user will at least be able to just distinguish between 'lowercase' and 'uppercase' in regular alphabet. Mucking around with what diacritics would or wouldn't be supported by such a toggle, say in a user preference, would be out of scope for this ticket.

**Comment by Stephen-Gates** [comment]
Sounds reasonable for this support release @mattRedBox.

@markwheels suggest this is labelled `support:Approved` and prioritised above #902.

**Comment by markwheels** [comment]
Thanks @mattRedBox  and @Stephen-Gates. I have marked this issue 'support:Approved'.

**Comment by Stephen-Gates** [comment]
Confirmed working in 1.1 beta
