### ISSUE TITLE
Difference between Selecting Replace/Find in main menu

### ISSUE THREAD

**Issue by mattRedBox** [ODIQueensland/data-curator#927]
One of the automated tests has picked up a minor bug in the Find->Replace
There's a difference between what Find/Replace does (from the main menu, not the slide out panel button) when searching for say 'two words' in a column that contains, say "two words", "two1 words"
There's logic which tries to search for text within the text that doesn't appear to be consistent.

**Comment by mattRedBox** [comment]
Hi @markwheels 
At the moment, this is blocking the CI tests run needed before building.

**Comment by Stephen-Gates** [comment]
@mattRedBox  Bug in 1.1 beta

Inconsistent results when finding and replacing using the menu vs using the slide out panel.

Using menu seems to ignore the "case sensitive" setting sometimes

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates, @markwheels 
I'm having trouble replicating this.
Could you please add possible steps that I might see this behaviour?

**Comment by Stephen-Gates** [comment]
Sorry @mattRedBox I can't replicate either

**Comment by mattRedBox** [comment]
Ok will close off then
