### ISSUE TITLE
Error exporting Data Package

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#934]
### Current Behaviour 

I exported a Data Package .zip file. It shows as 0 bytes. When I unzip it a file with the same name but . cpgz is appended and shows as bytes >0. When I try to open that, a .zip with the original name is created.

### Expected Behaviour
The exported Data Package .zip unzips to reveal the Data Package .JSON, CSV files and readme.metadata

### Steps to Reproduce

1. create a Data Package in Data Curator
2. attempt to open the Data Package .zip file

### Your Environment

* Data Curator version: 1.1.0
* Operating System and version: e.g. macOS Mojave 10.14.5

**Comment by chriswhong** [comment]
I am seeing this behavior as well in Data Curator 1.1.0 and MacOS 10.15.1 (Catalina)

**Comment by mattRedBox** [comment]
Hi @Stephen-Gates @chriswhong 
Atm negotiation is underway with our sponsors for  next round of work. I'll be able to look at this as soon as we get the go-ahead. Apologies for the delay.

**Comment by mattRedBox** [comment]
Ok Various bug fixes and upgrade libraries for this first pre-release which include fixing export - will keep this open however until have a beta release version to test.
