### ISSUE TITLE
Data Package panel displays two Contributor data entry sections on opening

### ISSUE THREAD

**Issue by Stephen-Gates** [ODIQueensland/data-curator#935]
### Current Behaviour (for problems)
On opening the Data Package panel two Contributor data entry sections are displayed

<img width="391" alt="Screenshot 2019-07-18 22 12 57" src="https://user-images.githubusercontent.com/9379524/61457468-b2749f80-a9ab-11e9-83a1-2e691db8d42a.png">

### Expected Behaviour
Zero Contributor data entry sections are displayed 

<img width="376" alt="Screenshot 2019-07-18 22 30 24" src="https://user-images.githubusercontent.com/9379524/61457487-bb657100-a9ab-11e9-97fa-f75490714c80.png">

### Steps to Reproduce

1. Open Data Curator 
2. Set Data Package properties

### Your Environment

* Data Curator version: 1.1.0
* Operating System and version: e.g. macOS Mojave 10.14.5

**Comment by mattRedBox** [comment]
Cannot replicate this, but see bug: #940

**Comment by mattRedBox** [comment]
Perhaps fixed with 1.2.0-alpha. Will close for now (in favour of #940)
