### ISSUE TITLE
processNextTick is not a function error opening data package

### ISSUE THREAD

**Issue by kayakr** [ODIQueensland/data-curator#937]
> Use the Issue Title above to provide a summary of the problem, feature request or other issue.
> Fill out the relevant sections below. Delete sections as appropriate.
> Provide as much detail as you can to help us help you.

### Desired Behaviour (for feature requests only)

I can open a data package previously saved by Data Curator.

### Current Behaviour (for problems)
In Data Curator 1.1.0:
* I try to open a data package from menu File > Open Data Package > zip from file... 
* Select .zip file previously saved from Data Curator 1.0.0
* `Open Data Package Error` displays with `processNextTick is not a function` message

### Expected Behaviour
> When reporting a problem, describe what should happen

The data package is opened, or a specific issue with the data package is pointed out, e.g. zip file has no json

### Steps to Reproduce
> When reporting a problem, provide a set of steps so others can reproduce the problem.
See above

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version: 1.1.0
* Operating System and version: e.g. macOS High Sierra 10.13.6

**Comment by kayakr** [comment]
Is https://github.com/archiverjs/node-archiver/issues/330 relevant? Data Curator appears to using archiver: 2.1.1

**Comment by mattRedBox** [comment]
See also #934

**Comment by mattRedBox** [comment]
Fixed with library upgrades/bug fix for this next beta release. Will keep this open until have a downloaded beta version to test.
