### ISSUE TITLE
Stuck with contributor without title, can't add/edit contributor

### ISSUE THREAD

**Issue by kayakr** [ODIQueensland/data-curator#940]
### Current Behaviour (for problems)
> When reporting a problem, describe what happens that isn't expected behaviour?

With error "At least 1 package contributor does not have a title." appears, can't edit Contributor via Provenance tab.

Can't save package, can't resolve error.

### Expected Behaviour
> When reporting a problem, describe what should happen

I can see and edit contributor record, or I can't open other tabs, e.g. Package until errors in Provenance tab are resolved.

### Steps to Reproduce
> When reporting a problem, provide a set of steps so others can reproduce the problem.

1. Created simple table with 3 rows, 4 columns.
2. Validated ok
3. Added provenance data.
4. Added data package data via Package sidebar
5. Added name, Title, Description, Version, License(s), Contributor
6. Contributor had name, email, etc. but not title.
7. Clicked on Provenance icon.
8. Try to Export, but error "At least 1 package contributor does not have a title." appears.
9. On Provenance tab, no contributors are listed.
10. On Provenance tab, +Add contributor button no longer adds form, does nothing.

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

* Data Curator version: 1.1.0
* Operating System and version: e.g. macOS High Sierra 10.13.6

**Comment by kayakr** [comment]
Restarted a new sheet, can fill in Add Contributor button doesn't work.
Can't save due to "At least 1 package contributor does not have a title" error.
See screenshot.
<img width="1433" alt="Screen Shot 2019-07-25 at 6 59 20 PM" src="https://user-images.githubusercontent.com/208184/61852879-a5593280-af0e-11e9-8b5b-8af75c50c373.png">

**Comment by mattRedBox** [comment]
Possible issue with key indexing.
