### ISSUE TITLE
Main README not clear can open TSV or other separators

### ISSUE THREAD

**Issue by peterjc** [ODIQueensland/data-curator#942]
### Desired Behaviour (for feature requests only)

Update the main README on GitHub

### Current Behaviour (for problems)

The main README for the project only explicitly mentions CSV and Excel, with no mention of TSV or other separators like semi-colons etc which might reasonably be supported (and indeed, from looking at issues like #14 in fact are supported).

You risk losing potential users by not making this clearer up front. It might help with search engine optimisation too?

Perhaps replace:

> * open data from a CSV or Microsoft Excel file

with something like:

> * open data from a CSV file (using commas, tabs - TSV, or other separators) or Microsoft Excel file

or:

> * open data from a CSV, TSV, or other plain text tables
> * open data from a Microsoft Excel file

I'm unclear if the link to CSV dialects link in the save section following this is relevant for input too?

### Expected Behaviour

1. Open https://github.com/ODIQueensland/data-curator/blob/develop/README.md
2. Search page for TSV, tab, separator
3. Matches to at least one of these keywords

### Steps to Reproduce
> When reporting a problem, provide a set of steps so others can reproduce the problem.

1. Open https://github.com/ODIQueensland/data-curator/blob/develop/README.md
2. Search page for TSV, tab, separator
3. No matches

### Your Environment
> Include details about the environment you experienced the problem - this will help us fix the bug quicker.

README.md as of 3ece41499a9925842ef24c8b68bf39c3fa608bb4 (default branch)

**Comment by Stephen-Gates** [comment]
Thanks @peterjc 

How's it read now?

**Comment by peterjc** [comment]
I think that’s an improvement - but recognise that a README file can easily get too long without clear editorial vision. I hope this feedback was useful, thanks for the quick reply.
