### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by JDziurlaj** [ODIQueensland/data-curator#978]
Can I get a status report on this project? I've noticed no issues have been triaged since Jul 2019, and the ODI AU site does not come up anymore.

**Comment by mattRedBox** [comment]
Hi @JDziurlaj 
ODI AU unfortunately no longer operates.
The project still runs and does so according to our sponsor's needs/requests. They have indicated that they would like to sponsor further work in 2020. Hoping to hear something more definitive over the coming month.

**Comment by mattRedBox** [comment]
Hi @JDziurlaj 
It looks like we'll be given the OK over next month or so to start for next release.
